// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/ad_unit_service.proto

package admanager

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request object for GetAdUnit method.
type GetAdUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The resource name of the AdUnit.
	// Format: `networks/{network_code}/adUnits/{ad_unit_id}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAdUnitRequest) Reset() {
	*x = GetAdUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdUnitRequest) ProtoMessage() {}

func (x *GetAdUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdUnitRequest.ProtoReflect.Descriptor instead.
func (*GetAdUnitRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request object for ListAdUnits method.
type ListAdUnitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The parent, which owns this collection of AdUnits.
	// Format: `networks/{network_code}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of AdUnits to return. The service may return
	// fewer than this value. If unspecified, at most 50 ad units will be
	// returned. The maximum value is 1000; values above 1000 will be coerced to
	// 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListAdUnits` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListAdUnits` must match
	// the call that provided the page token.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Expression to filter the response.
	// See syntax details at
	// https://developers.google.com/ad-manager/api/beta/filters
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Expression to specify sorting order.
	// See syntax details at
	// https://developers.google.com/ad-manager/api/beta/filters#order
	OrderBy string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Optional. Number of individual resources to skip while paginating.
	Skip int32 `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *ListAdUnitsRequest) Reset() {
	*x = ListAdUnitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdUnitsRequest) ProtoMessage() {}

func (x *ListAdUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdUnitsRequest.ProtoReflect.Descriptor instead.
func (*ListAdUnitsRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdUnitsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAdUnitsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdUnitsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAdUnitsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAdUnitsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListAdUnitsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// Response object for ListAdUnitsRequest containing matching AdUnit resources.
type ListAdUnitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The AdUnit from the specified network.
	AdUnits []*AdUnit `protobuf:"bytes,1,rep,name=ad_units,json=adUnits,proto3" json:"ad_units,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of AdUnits.
	// If a filter was included in the request, this reflects the total number
	// after the filtering is applied.
	//
	// `total_size` will not be calculated in the response unless it has been
	// included in a response field mask. The response field mask can be provided
	// to the method by using the URL parameter `$fields` or `fields`, or by using
	// the HTTP/gRPC header `X-Goog-FieldMask`.
	//
	// For more information, see
	// https://developers.google.com/ad-manager/api/beta/field-masks
	TotalSize int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
}

func (x *ListAdUnitsResponse) Reset() {
	*x = ListAdUnitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdUnitsResponse) ProtoMessage() {}

func (x *ListAdUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdUnitsResponse.ProtoReflect.Descriptor instead.
func (*ListAdUnitsResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAdUnitsResponse) GetAdUnits() []*AdUnit {
	if x != nil {
		return x.AdUnits
	}
	return nil
}

func (x *ListAdUnitsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAdUnitsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Request object for ListAdUnitSizes method.
type ListAdUnitSizesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The parent, which owns this collection of AdUnitSizes.
	// Format: `networks/{network_code}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of AdUnitSizes to return. The service may
	// return fewer than this value. If unspecified, at most 50 ad unit sizes will
	// be returned. The maximum value is 1000; values above 1000 will be coerced
	// to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListAdUnitSizes` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListAdUnitSizes` must
	// match the call that provided the page token.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Expression to filter the response.
	// See syntax details at
	// https://developers.google.com/ad-manager/api/beta/filters
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Expression to specify sorting order.
	// See syntax details at
	// https://developers.google.com/ad-manager/api/beta/filters#order
	OrderBy string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Optional. Number of individual resources to skip while paginating.
	Skip int32 `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *ListAdUnitSizesRequest) Reset() {
	*x = ListAdUnitSizesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdUnitSizesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdUnitSizesRequest) ProtoMessage() {}

func (x *ListAdUnitSizesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdUnitSizesRequest.ProtoReflect.Descriptor instead.
func (*ListAdUnitSizesRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAdUnitSizesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAdUnitSizesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdUnitSizesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAdUnitSizesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAdUnitSizesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListAdUnitSizesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// Response object for ListAdUnitSizesRequest containing matching AdUnitSizes.
type ListAdUnitSizesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The AdUnitSizes from the specified network.
	AdUnitSizes []*AdUnitSize `protobuf:"bytes,1,rep,name=ad_unit_sizes,json=adUnitSizes,proto3" json:"ad_unit_sizes,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of AdUnitSizes.
	// If a filter was included in the request, this reflects the total number
	// after the filtering is applied.
	//
	// `total_size` will not be calculated in the response unless it has been
	// included in a response field mask. The response field mask can be provided
	// to the method by using the URL parameter `$fields` or `fields`, or by using
	// the HTTP/gRPC header `X-Goog-FieldMask`.
	//
	// For more information, see
	// https://developers.google.com/ad-manager/api/beta/field-masks
	TotalSize int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
}

func (x *ListAdUnitSizesResponse) Reset() {
	*x = ListAdUnitSizesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdUnitSizesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdUnitSizesResponse) ProtoMessage() {}

func (x *ListAdUnitSizesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdUnitSizesResponse.ProtoReflect.Descriptor instead.
func (*ListAdUnitSizesResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdUnitSizesResponse) GetAdUnitSizes() []*AdUnitSize {
	if x != nil {
		return x.AdUnitSizes
	}
	return nil
}

func (x *ListAdUnitSizesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAdUnitSizesResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_google_ads_admanager_v1_ad_unit_service_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_ad_unit_service_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x5f, 0x75, 0x6e, 0x69,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x27, 0xe0,
	0x41, 0x02, 0xfa, 0x41, 0x21, 0x0a, 0x1f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xf2, 0x01, 0x0a,
	0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x28, 0xe0, 0x41, 0x02, 0xfa, 0x41, 0x22, 0x0a, 0x20, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x01,
	0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x01,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x17, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x52, 0x04, 0x73, 0x6b, 0x69,
	0x70, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x61, 0x64, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x07, 0x61, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xf6, 0x01, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x28, 0xe0, 0x41, 0x02, 0xfa, 0x41, 0x22, 0x0a,
	0x20, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x03, 0xe0, 0x41,
	0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x03, 0xe0, 0x41, 0x01, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x03, 0xe0, 0x41, 0x01, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03,
	0xe0, 0x41, 0x01, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x17, 0x0a, 0x04,
	0x73, 0x6b, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x22, 0xa9, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0d, 0x61, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x0b, 0x61,
	0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a,
	0x65, 0x32, 0x80, 0x04, 0x0a, 0x0d, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x87, 0x01, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x29, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61,
	0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x2e, 0xda,
	0x41, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x76,
	0x31, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x3d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x2f, 0x2a, 0x2f, 0x61, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x2f, 0x2a, 0x7d, 0x12, 0x9a, 0x01,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x2b, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0xda, 0x41, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x76, 0x31, 0x2f, 0x7b,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x3d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f,
	0x2a, 0x7d, 0x2f, 0x61, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0xaa, 0x01, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x2f,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x55,
	0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x30, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x34, 0xda, 0x41, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x25, 0x12, 0x23, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x3d,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x2a, 0x7d, 0x2f, 0x61, 0x64, 0x55, 0x6e,
	0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x1a, 0x1b, 0xca, 0x41, 0x18, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x42, 0xc6, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x42, 0x12, 0x41, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69,
	0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xaa, 0x02, 0x17, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5c,
	0x41, 0x64, 0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5c, 0x56, 0x31,
	0xea, 0x02, 0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73, 0x3a, 0x3a,
	0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_ad_unit_service_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_ad_unit_service_proto_rawDescData = file_google_ads_admanager_v1_ad_unit_service_proto_rawDesc
)

func file_google_ads_admanager_v1_ad_unit_service_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_ad_unit_service_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_ad_unit_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_ad_unit_service_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_ad_unit_service_proto_rawDescData
}

var file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_google_ads_admanager_v1_ad_unit_service_proto_goTypes = []any{
	(*GetAdUnitRequest)(nil),        // 0: google.ads.admanager.v1.GetAdUnitRequest
	(*ListAdUnitsRequest)(nil),      // 1: google.ads.admanager.v1.ListAdUnitsRequest
	(*ListAdUnitsResponse)(nil),     // 2: google.ads.admanager.v1.ListAdUnitsResponse
	(*ListAdUnitSizesRequest)(nil),  // 3: google.ads.admanager.v1.ListAdUnitSizesRequest
	(*ListAdUnitSizesResponse)(nil), // 4: google.ads.admanager.v1.ListAdUnitSizesResponse
	(*AdUnit)(nil),                  // 5: google.ads.admanager.v1.AdUnit
	(*AdUnitSize)(nil),              // 6: google.ads.admanager.v1.AdUnitSize
}
var file_google_ads_admanager_v1_ad_unit_service_proto_depIdxs = []int32{
	5, // 0: google.ads.admanager.v1.ListAdUnitsResponse.ad_units:type_name -> google.ads.admanager.v1.AdUnit
	6, // 1: google.ads.admanager.v1.ListAdUnitSizesResponse.ad_unit_sizes:type_name -> google.ads.admanager.v1.AdUnitSize
	0, // 2: google.ads.admanager.v1.AdUnitService.GetAdUnit:input_type -> google.ads.admanager.v1.GetAdUnitRequest
	1, // 3: google.ads.admanager.v1.AdUnitService.ListAdUnits:input_type -> google.ads.admanager.v1.ListAdUnitsRequest
	3, // 4: google.ads.admanager.v1.AdUnitService.ListAdUnitSizes:input_type -> google.ads.admanager.v1.ListAdUnitSizesRequest
	5, // 5: google.ads.admanager.v1.AdUnitService.GetAdUnit:output_type -> google.ads.admanager.v1.AdUnit
	2, // 6: google.ads.admanager.v1.AdUnitService.ListAdUnits:output_type -> google.ads.admanager.v1.ListAdUnitsResponse
	4, // 7: google.ads.admanager.v1.AdUnitService.ListAdUnitSizes:output_type -> google.ads.admanager.v1.ListAdUnitSizesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_ad_unit_service_proto_init() }
func file_google_ads_admanager_v1_ad_unit_service_proto_init() {
	if File_google_ads_admanager_v1_ad_unit_service_proto != nil {
		return
	}
	file_google_ads_admanager_v1_ad_unit_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdUnitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdUnitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdUnitSizesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdUnitSizesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_ad_unit_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_admanager_v1_ad_unit_service_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_ad_unit_service_proto_depIdxs,
		MessageInfos:      file_google_ads_admanager_v1_ad_unit_service_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_ad_unit_service_proto = out.File
	file_google_ads_admanager_v1_ad_unit_service_proto_rawDesc = nil
	file_google_ads_admanager_v1_ad_unit_service_proto_goTypes = nil
	file_google_ads_admanager_v1_ad_unit_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdUnitServiceClient is the client API for AdUnitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdUnitServiceClient interface {
	// API to retrieve an AdUnit object.
	GetAdUnit(ctx context.Context, in *GetAdUnitRequest, opts ...grpc.CallOption) (*AdUnit, error)
	// API to retrieve a list of AdUnit objects.
	ListAdUnits(ctx context.Context, in *ListAdUnitsRequest, opts ...grpc.CallOption) (*ListAdUnitsResponse, error)
	// API to retrieve a list of AdUnitSize objects.
	ListAdUnitSizes(ctx context.Context, in *ListAdUnitSizesRequest, opts ...grpc.CallOption) (*ListAdUnitSizesResponse, error)
}

type adUnitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdUnitServiceClient(cc grpc.ClientConnInterface) AdUnitServiceClient {
	return &adUnitServiceClient{cc}
}

func (c *adUnitServiceClient) GetAdUnit(ctx context.Context, in *GetAdUnitRequest, opts ...grpc.CallOption) (*AdUnit, error) {
	out := new(AdUnit)
	err := c.cc.Invoke(ctx, "/google.ads.admanager.v1.AdUnitService/GetAdUnit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adUnitServiceClient) ListAdUnits(ctx context.Context, in *ListAdUnitsRequest, opts ...grpc.CallOption) (*ListAdUnitsResponse, error) {
	out := new(ListAdUnitsResponse)
	err := c.cc.Invoke(ctx, "/google.ads.admanager.v1.AdUnitService/ListAdUnits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adUnitServiceClient) ListAdUnitSizes(ctx context.Context, in *ListAdUnitSizesRequest, opts ...grpc.CallOption) (*ListAdUnitSizesResponse, error) {
	out := new(ListAdUnitSizesResponse)
	err := c.cc.Invoke(ctx, "/google.ads.admanager.v1.AdUnitService/ListAdUnitSizes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdUnitServiceServer is the server API for AdUnitService service.
type AdUnitServiceServer interface {
	// API to retrieve an AdUnit object.
	GetAdUnit(context.Context, *GetAdUnitRequest) (*AdUnit, error)
	// API to retrieve a list of AdUnit objects.
	ListAdUnits(context.Context, *ListAdUnitsRequest) (*ListAdUnitsResponse, error)
	// API to retrieve a list of AdUnitSize objects.
	ListAdUnitSizes(context.Context, *ListAdUnitSizesRequest) (*ListAdUnitSizesResponse, error)
}

// UnimplementedAdUnitServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdUnitServiceServer struct {
}

func (*UnimplementedAdUnitServiceServer) GetAdUnit(context.Context, *GetAdUnitRequest) (*AdUnit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdUnit not implemented")
}
func (*UnimplementedAdUnitServiceServer) ListAdUnits(context.Context, *ListAdUnitsRequest) (*ListAdUnitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdUnits not implemented")
}
func (*UnimplementedAdUnitServiceServer) ListAdUnitSizes(context.Context, *ListAdUnitSizesRequest) (*ListAdUnitSizesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdUnitSizes not implemented")
}

func RegisterAdUnitServiceServer(s *grpc.Server, srv AdUnitServiceServer) {
	s.RegisterService(&_AdUnitService_serviceDesc, srv)
}

func _AdUnitService_GetAdUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdUnitServiceServer).GetAdUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.admanager.v1.AdUnitService/GetAdUnit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdUnitServiceServer).GetAdUnit(ctx, req.(*GetAdUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdUnitService_ListAdUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdUnitServiceServer).ListAdUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.admanager.v1.AdUnitService/ListAdUnits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdUnitServiceServer).ListAdUnits(ctx, req.(*ListAdUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdUnitService_ListAdUnitSizes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdUnitSizesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdUnitServiceServer).ListAdUnitSizes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.admanager.v1.AdUnitService/ListAdUnitSizes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdUnitServiceServer).ListAdUnitSizes(ctx, req.(*ListAdUnitSizesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdUnitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.admanager.v1.AdUnitService",
	HandlerType: (*AdUnitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdUnit",
			Handler:    _AdUnitService_GetAdUnit_Handler,
		},
		{
			MethodName: "ListAdUnits",
			Handler:    _AdUnitService_ListAdUnits_Handler,
		},
		{
			MethodName: "ListAdUnitSizes",
			Handler:    _AdUnitService_ListAdUnitSizes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/admanager/v1/ad_unit_service.proto",
}
