// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/company_credit_status_enum.proto

package admanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The credit status of a company.
//
// Credit statuses specify the credit-worthiness of a company and affect the
// ad serving of campaigns belonging to the company.
//
// In basic settings, only the
// [ACTIVE][google.ads.admanager.v1.CompanyCreditStatusEnum.CompanyCreditStatus.ACTIVE]
// and
// [INACTIVE][google.ads.admanager.v1.CompanyCreditStatusEnum.CompanyCreditStatus.INACTIVE]
// credit statuses are applicable. In advance settings, all credit statuses
// are applicable.
type CompanyCreditStatusEnum_CompanyCreditStatus int32

const (
	// No value specified
	CompanyCreditStatusEnum_COMPANY_CREDIT_STATUS_UNSPECIFIED CompanyCreditStatusEnum_CompanyCreditStatus = 0
	// The company's credit status is active.
	//
	// Line items belonging to the company can serve.
	//
	// This credit status is the default for basic settings and is available in
	// both basic and advance settings.
	CompanyCreditStatusEnum_ACTIVE CompanyCreditStatusEnum_CompanyCreditStatus = 1
	// The company's credit status is inactive.
	//
	// Line items belonging to the company cannot be activated. However, line
	// items that were activated before the credit status changed will remain
	// active. New orders or line items belonging to the company cannot be
	// created.
	//
	// Companies with this credit status will be hidden by default in company
	// search results.
	//
	// This credit status is available in both basic and advance settings.
	CompanyCreditStatusEnum_INACTIVE CompanyCreditStatusEnum_CompanyCreditStatus = 2
	// The company's credit status is on hold.
	//
	// Line items belonging to the company cannot be activated. However, line
	// items that were activated before the credit status changed will remain
	// active. New orders or line items belonging to the company can be
	// created.
	//
	// This credit status is the default in advance settings and is only
	// available in advance settings.
	CompanyCreditStatusEnum_ON_HOLD CompanyCreditStatusEnum_CompanyCreditStatus = 3
	// The company's credit status is stopped.
	//
	// Line items belonging to the company cannot be activated. However, line
	// items that were activated before the credit status changed will remain
	// active. New orders or line items belonging to the company cannot be
	// created.
	//
	// This credit status is only available in advance settings.
	CompanyCreditStatusEnum_STOP CompanyCreditStatusEnum_CompanyCreditStatus = 4
	// The company's credit status is blocked.
	//
	// All active line items belonging to the company will stop serving with
	// immediate effect. Line items belonging to the company cannot be
	// activated, and new orders or line items belonging to the company cannot
	// be created.
	//
	// This credit status is only available in advance settings.
	CompanyCreditStatusEnum_BLOCKED CompanyCreditStatusEnum_CompanyCreditStatus = 5
)

// Enum value maps for CompanyCreditStatusEnum_CompanyCreditStatus.
var (
	CompanyCreditStatusEnum_CompanyCreditStatus_name = map[int32]string{
		0: "COMPANY_CREDIT_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "ON_HOLD",
		4: "STOP",
		5: "BLOCKED",
	}
	CompanyCreditStatusEnum_CompanyCreditStatus_value = map[string]int32{
		"COMPANY_CREDIT_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                            1,
		"INACTIVE":                          2,
		"ON_HOLD":                           3,
		"STOP":                              4,
		"BLOCKED":                           5,
	}
)

func (x CompanyCreditStatusEnum_CompanyCreditStatus) Enum() *CompanyCreditStatusEnum_CompanyCreditStatus {
	p := new(CompanyCreditStatusEnum_CompanyCreditStatus)
	*p = x
	return p
}

func (x CompanyCreditStatusEnum_CompanyCreditStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompanyCreditStatusEnum_CompanyCreditStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_company_credit_status_enum_proto_enumTypes[0].Descriptor()
}

func (CompanyCreditStatusEnum_CompanyCreditStatus) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_company_credit_status_enum_proto_enumTypes[0]
}

func (x CompanyCreditStatusEnum_CompanyCreditStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompanyCreditStatusEnum_CompanyCreditStatus.Descriptor instead.
func (CompanyCreditStatusEnum_CompanyCreditStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescGZIP(), []int{0, 0}
}

// Wrapper message for
// [CompanyCreditStatus][google.ads.admanager.v1.CompanyCreditStatusEnum.CompanyCreditStatus]
type CompanyCreditStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompanyCreditStatusEnum) Reset() {
	*x = CompanyCreditStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_company_credit_status_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyCreditStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyCreditStatusEnum) ProtoMessage() {}

func (x *CompanyCreditStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_company_credit_status_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyCreditStatusEnum.ProtoReflect.Descriptor instead.
func (*CompanyCreditStatusEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_admanager_v1_company_credit_status_enum_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x95, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22,
	0x7a, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e,
	0x59, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x5f, 0x48, 0x4f,
	0x4c, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x05, 0x42, 0xd0, 0x01, 0x0a, 0x1b,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61,
	0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x1c, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x45, 0x6e, 0x75, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xaa, 0x02, 0x17,
	0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x5c, 0x41, 0x64, 0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5c, 0x56,
	0x31, 0xea, 0x02, 0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73, 0x3a,
	0x3a, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescData = file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDesc
)

func file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDescData
}

var file_google_ads_admanager_v1_company_credit_status_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_admanager_v1_company_credit_status_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_admanager_v1_company_credit_status_enum_proto_goTypes = []any{
	(CompanyCreditStatusEnum_CompanyCreditStatus)(0), // 0: google.ads.admanager.v1.CompanyCreditStatusEnum.CompanyCreditStatus
	(*CompanyCreditStatusEnum)(nil),                  // 1: google.ads.admanager.v1.CompanyCreditStatusEnum
}
var file_google_ads_admanager_v1_company_credit_status_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_company_credit_status_enum_proto_init() }
func file_google_ads_admanager_v1_company_credit_status_enum_proto_init() {
	if File_google_ads_admanager_v1_company_credit_status_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_company_credit_status_enum_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CompanyCreditStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_admanager_v1_company_credit_status_enum_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_company_credit_status_enum_proto_depIdxs,
		EnumInfos:         file_google_ads_admanager_v1_company_credit_status_enum_proto_enumTypes,
		MessageInfos:      file_google_ads_admanager_v1_company_credit_status_enum_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_company_credit_status_enum_proto = out.File
	file_google_ads_admanager_v1_company_credit_status_enum_proto_rawDesc = nil
	file_google_ads_admanager_v1_company_credit_status_enum_proto_goTypes = nil
	file_google_ads_admanager_v1_company_credit_status_enum_proto_depIdxs = nil
}
