// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/custom_field_value.proto

package admanager

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A value for a CustomField on a resource.
type CustomFieldValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The custom field for which this is a value.
	// Format: "networks/{network_code}/customFields/{custom_field_id}"
	CustomField string `protobuf:"bytes,1,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	// Required. A typed value representation of the value.
	Value *CustomFieldValue_Value `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *CustomFieldValue) Reset() {
	*x = CustomFieldValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldValue) ProtoMessage() {}

func (x *CustomFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldValue.ProtoReflect.Descriptor instead.
func (*CustomFieldValue) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_value_proto_rawDescGZIP(), []int{0}
}

func (x *CustomFieldValue) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

func (x *CustomFieldValue) GetValue() *CustomFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Represent custom field value type.
// Next Id: 5
type CustomFieldValue_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The value of this field.
	//
	// Types that are assignable to Value:
	//
	//	*CustomFieldValue_Value_DropdownValue
	//	*CustomFieldValue_Value_StringValue
	//	*CustomFieldValue_Value_NumberValue
	//	*CustomFieldValue_Value_ToggleValue
	Value isCustomFieldValue_Value_Value `protobuf_oneof:"value"`
}

func (x *CustomFieldValue_Value) Reset() {
	*x = CustomFieldValue_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldValue_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldValue_Value) ProtoMessage() {}

func (x *CustomFieldValue_Value) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldValue_Value.ProtoReflect.Descriptor instead.
func (*CustomFieldValue_Value) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_value_proto_rawDescGZIP(), []int{0, 0}
}

func (m *CustomFieldValue_Value) GetValue() isCustomFieldValue_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CustomFieldValue_Value) GetDropdownValue() int64 {
	if x, ok := x.GetValue().(*CustomFieldValue_Value_DropdownValue); ok {
		return x.DropdownValue
	}
	return 0
}

func (x *CustomFieldValue_Value) GetStringValue() string {
	if x, ok := x.GetValue().(*CustomFieldValue_Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *CustomFieldValue_Value) GetNumberValue() float64 {
	if x, ok := x.GetValue().(*CustomFieldValue_Value_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (x *CustomFieldValue_Value) GetToggleValue() bool {
	if x, ok := x.GetValue().(*CustomFieldValue_Value_ToggleValue); ok {
		return x.ToggleValue
	}
	return false
}

type isCustomFieldValue_Value_Value interface {
	isCustomFieldValue_Value_Value()
}

type CustomFieldValue_Value_DropdownValue struct {
	// The custom_field_option_id, if the CustomFieldDataType is DROPDOWN.
	DropdownValue int64 `protobuf:"varint,1,opt,name=dropdown_value,json=dropdownValue,proto3,oneof"`
}

type CustomFieldValue_Value_StringValue struct {
	// The value, if the CustomFieldDataType is STRING.
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CustomFieldValue_Value_NumberValue struct {
	// The value, if the CustomFieldDataType is NUMBER.
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type CustomFieldValue_Value_ToggleValue struct {
	// The value, if the CustomFieldDataType is TOGGLE.
	ToggleValue bool `protobuf:"varint,4,opt,name=toggle_value,json=toggleValue,proto3,oneof"`
}

func (*CustomFieldValue_Value_DropdownValue) isCustomFieldValue_Value_Value() {}

func (*CustomFieldValue_Value_StringValue) isCustomFieldValue_Value_Value() {}

func (*CustomFieldValue_Value_NumberValue) isCustomFieldValue_Value_Value() {}

func (*CustomFieldValue_Value_ToggleValue) isCustomFieldValue_Value_Value() {}

var File_google_ads_admanager_v1_custom_field_value_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_custom_field_value_proto_rawDesc = []byte{
	0x0a, 0x30, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61,
	0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9, 0x02, 0x0a, 0x10, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4f, 0x0a, 0x0c,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x2c, 0xe0, 0x41, 0x02, 0xfa, 0x41, 0x26, 0x0a, 0x24, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x4f, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x03, 0xe0,
	0x41, 0x02, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x1a, 0xa8,
	0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x0e, 0x64, 0x72, 0x6f, 0x70,
	0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x0d, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0xc9, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x42, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xaa, 0x02,
	0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x5c, 0x41, 0x64, 0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5c,
	0x56, 0x31, 0xea, 0x02, 0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73,
	0x3a, 0x3a, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_custom_field_value_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_custom_field_value_proto_rawDescData = file_google_ads_admanager_v1_custom_field_value_proto_rawDesc
)

func file_google_ads_admanager_v1_custom_field_value_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_custom_field_value_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_custom_field_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_custom_field_value_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_custom_field_value_proto_rawDescData
}

var file_google_ads_admanager_v1_custom_field_value_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_ads_admanager_v1_custom_field_value_proto_goTypes = []any{
	(*CustomFieldValue)(nil),       // 0: google.ads.admanager.v1.CustomFieldValue
	(*CustomFieldValue_Value)(nil), // 1: google.ads.admanager.v1.CustomFieldValue.Value
}
var file_google_ads_admanager_v1_custom_field_value_proto_depIdxs = []int32{
	1, // 0: google.ads.admanager.v1.CustomFieldValue.value:type_name -> google.ads.admanager.v1.CustomFieldValue.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_custom_field_value_proto_init() }
func file_google_ads_admanager_v1_custom_field_value_proto_init() {
	if File_google_ads_admanager_v1_custom_field_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldValue_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[0].OneofWrappers = []any{}
	file_google_ads_admanager_v1_custom_field_value_proto_msgTypes[1].OneofWrappers = []any{
		(*CustomFieldValue_Value_DropdownValue)(nil),
		(*CustomFieldValue_Value_StringValue)(nil),
		(*CustomFieldValue_Value_NumberValue)(nil),
		(*CustomFieldValue_Value_ToggleValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_custom_field_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_admanager_v1_custom_field_value_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_custom_field_value_proto_depIdxs,
		MessageInfos:      file_google_ads_admanager_v1_custom_field_value_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_custom_field_value_proto = out.File
	file_google_ads_admanager_v1_custom_field_value_proto_rawDesc = nil
	file_google_ads_admanager_v1_custom_field_value_proto_goTypes = nil
	file_google_ads_admanager_v1_custom_field_value_proto_depIdxs = nil
}
