// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/custom_targeting_value_enums.proto

package admanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the custom targeting value.
type CustomTargetingValueStatusEnum_CustomTargetingValueStatus int32

const (
	// Not specified value.
	CustomTargetingValueStatusEnum_CUSTOM_TARGETING_VALUE_STATUS_UNSPECIFIED CustomTargetingValueStatusEnum_CustomTargetingValueStatus = 0
	// Custom targeting value is active.
	CustomTargetingValueStatusEnum_ACTIVE CustomTargetingValueStatusEnum_CustomTargetingValueStatus = 1
	// Custom targeting value is inactive.
	CustomTargetingValueStatusEnum_INACTIVE CustomTargetingValueStatusEnum_CustomTargetingValueStatus = 2
)

// Enum value maps for CustomTargetingValueStatusEnum_CustomTargetingValueStatus.
var (
	CustomTargetingValueStatusEnum_CustomTargetingValueStatus_name = map[int32]string{
		0: "CUSTOM_TARGETING_VALUE_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
	}
	CustomTargetingValueStatusEnum_CustomTargetingValueStatus_value = map[string]int32{
		"CUSTOM_TARGETING_VALUE_STATUS_UNSPECIFIED": 0,
		"ACTIVE":   1,
		"INACTIVE": 2,
	}
)

func (x CustomTargetingValueStatusEnum_CustomTargetingValueStatus) Enum() *CustomTargetingValueStatusEnum_CustomTargetingValueStatus {
	p := new(CustomTargetingValueStatusEnum_CustomTargetingValueStatus)
	*p = x
	return p
}

func (x CustomTargetingValueStatusEnum_CustomTargetingValueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomTargetingValueStatusEnum_CustomTargetingValueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes[0].Descriptor()
}

func (CustomTargetingValueStatusEnum_CustomTargetingValueStatus) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes[0]
}

func (x CustomTargetingValueStatusEnum_CustomTargetingValueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomTargetingValueStatusEnum_CustomTargetingValueStatus.Descriptor instead.
func (CustomTargetingValueStatusEnum_CustomTargetingValueStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescGZIP(), []int{0, 0}
}

// Match type of the custom targeting value.
type CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType int32

const (
	// Not specified value.
	CustomTargetingValueMatchTypeEnum_CUSTOM_TARGETING_VALUE_MATCH_TYPE_UNSPECIFIED CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 0
	// Used for exact matching. For example, the targeting value car=honda will
	// only match to the ad request car=honda.
	CustomTargetingValueMatchTypeEnum_EXACT CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 1
	// Used for lenient matching when at least one of the words in the ad
	// request matches the targeted value. The targeting value car=honda will
	// match to ad requests containing the word honda. So ad requests car=honda
	// or car=honda civic or car=buy honda or car=how much does a honda cost
	// will all have the line item delivered.
	// This match type can not be used within an audience segment rule.
	CustomTargetingValueMatchTypeEnum_BROAD CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 2
	// Used for 'starts with' matching when the first few characters in the ad
	// request match all of the characters in the targeted value. The targeting
	// value car=honda will match to ad requests car=honda or car=hondas for
	// sale but not to car=I want a honda.
	CustomTargetingValueMatchTypeEnum_PREFIX CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 3
	// This is a combination of MatchType#BROAD and MatchType#PREFIX matching.
	// The targeting value car=honda will match to ad requests that contain
	// words that start with the characters in the targeted value, for example
	// with car=civic hondas.
	// This match type can not be used within an audience segment rule.
	CustomTargetingValueMatchTypeEnum_BROAD_PREFIX CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 4
	// Used for 'ends with' matching when the last characters in the ad request
	// match all of the characters in the targeted value. The targeting value
	// car=honda will match with ad requests car=honda or car=I want a honda but
	// not to car=hondas for sale.
	// This match type can not be used within line item targeting.
	CustomTargetingValueMatchTypeEnum_SUFFIX CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 5
	// Used for 'within' matching when the string in the ad request contains the
	// string in the targeted value. The targeting value car=honda will match
	// with ad requests car=honda, car=I want a honda, and also with car=hondas
	// for sale, but not with car=misspelled hond a. This match type can not be
	// used within line item targeting.
	CustomTargetingValueMatchTypeEnum_CONTAINS CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType = 6
)

// Enum value maps for CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType.
var (
	CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType_name = map[int32]string{
		0: "CUSTOM_TARGETING_VALUE_MATCH_TYPE_UNSPECIFIED",
		1: "EXACT",
		2: "BROAD",
		3: "PREFIX",
		4: "BROAD_PREFIX",
		5: "SUFFIX",
		6: "CONTAINS",
	}
	CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType_value = map[string]int32{
		"CUSTOM_TARGETING_VALUE_MATCH_TYPE_UNSPECIFIED": 0,
		"EXACT":        1,
		"BROAD":        2,
		"PREFIX":       3,
		"BROAD_PREFIX": 4,
		"SUFFIX":       5,
		"CONTAINS":     6,
	}
)

func (x CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) Enum() *CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType {
	p := new(CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType)
	*p = x
	return p
}

func (x CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes[1].Descriptor()
}

func (CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes[1]
}

func (x CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType.Descriptor instead.
func (CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescGZIP(), []int{1, 0}
}

// Wrapper message for
// [CustomTargetingValueStatus][google.ads.admanager.v1.CustomTargetingValueStatusEnum.CustomTargetingValueStatus]
type CustomTargetingValueStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomTargetingValueStatusEnum) Reset() {
	*x = CustomTargetingValueStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomTargetingValueStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomTargetingValueStatusEnum) ProtoMessage() {}

func (x *CustomTargetingValueStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTargetingValueStatusEnum.ProtoReflect.Descriptor instead.
func (*CustomTargetingValueStatusEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescGZIP(), []int{0}
}

// Wrapper message for
// [CustomTargetingValueMatchType][google.ads.admanager.v1.CustomTargetingValueMatchTypeEnum.CustomTargetingValueMatchType]
type CustomTargetingValueMatchTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomTargetingValueMatchTypeEnum) Reset() {
	*x = CustomTargetingValueMatchTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomTargetingValueMatchTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomTargetingValueMatchTypeEnum) ProtoMessage() {}

func (x *CustomTargetingValueMatchTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTargetingValueMatchTypeEnum.ProtoReflect.Descriptor instead.
func (*CustomTargetingValueMatchTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescGZIP(), []int{1}
}

var File_google_ads_admanager_v1_custom_targeting_value_enums_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x87, 0x01, 0x0a, 0x1e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x65, 0x0a, 0x1a, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x29, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d,
	0x5f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x22,
	0xc6, 0x01, 0x0a, 0x21, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0xa0, 0x01, 0x0a, 0x1d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x2d, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x56, 0x41, 0x4c, 0x55,
	0x45, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x58,
	0x41, 0x43, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x42, 0x52, 0x4f, 0x41, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x04, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x55, 0x46, 0x46, 0x49, 0x58, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f,
	0x4e, 0x54, 0x41, 0x49, 0x4e, 0x53, 0x10, 0x06, 0x42, 0xd2, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x1e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69,
	0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xaa, 0x02, 0x17, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5c,
	0x41, 0x64, 0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5c, 0x56, 0x31,
	0xea, 0x02, 0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73, 0x3a, 0x3a,
	0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescData = file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDesc
)

func file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDescData
}

var file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_ads_admanager_v1_custom_targeting_value_enums_proto_goTypes = []any{
	(CustomTargetingValueStatusEnum_CustomTargetingValueStatus)(0),       // 0: google.ads.admanager.v1.CustomTargetingValueStatusEnum.CustomTargetingValueStatus
	(CustomTargetingValueMatchTypeEnum_CustomTargetingValueMatchType)(0), // 1: google.ads.admanager.v1.CustomTargetingValueMatchTypeEnum.CustomTargetingValueMatchType
	(*CustomTargetingValueStatusEnum)(nil),                               // 2: google.ads.admanager.v1.CustomTargetingValueStatusEnum
	(*CustomTargetingValueMatchTypeEnum)(nil),                            // 3: google.ads.admanager.v1.CustomTargetingValueMatchTypeEnum
}
var file_google_ads_admanager_v1_custom_targeting_value_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_custom_targeting_value_enums_proto_init() }
func file_google_ads_admanager_v1_custom_targeting_value_enums_proto_init() {
	if File_google_ads_admanager_v1_custom_targeting_value_enums_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CustomTargetingValueStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CustomTargetingValueMatchTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_admanager_v1_custom_targeting_value_enums_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_custom_targeting_value_enums_proto_depIdxs,
		EnumInfos:         file_google_ads_admanager_v1_custom_targeting_value_enums_proto_enumTypes,
		MessageInfos:      file_google_ads_admanager_v1_custom_targeting_value_enums_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_custom_targeting_value_enums_proto = out.File
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_rawDesc = nil
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_goTypes = nil
	file_google_ads_admanager_v1_custom_targeting_value_enums_proto_depIdxs = nil
}
