// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/custom_field_enums.proto

package admanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The data type for a CustomField.
type CustomFieldDataTypeEnum_CustomFieldDataType int32

const (
	// No value specified
	CustomFieldDataTypeEnum_CUSTOM_FIELD_DATA_TYPE_UNSPECIFIED CustomFieldDataTypeEnum_CustomFieldDataType = 0
	// A string field
	//
	// The max length is 255 characters.
	CustomFieldDataTypeEnum_STRING CustomFieldDataTypeEnum_CustomFieldDataType = 1
	// A number field.
	CustomFieldDataTypeEnum_NUMBER CustomFieldDataTypeEnum_CustomFieldDataType = 2
	// A "Yes" or "No" toggle field.
	CustomFieldDataTypeEnum_TOGGLE CustomFieldDataTypeEnum_CustomFieldDataType = 3
	// A drop-down field.
	CustomFieldDataTypeEnum_DROP_DOWN CustomFieldDataTypeEnum_CustomFieldDataType = 4
)

// Enum value maps for CustomFieldDataTypeEnum_CustomFieldDataType.
var (
	CustomFieldDataTypeEnum_CustomFieldDataType_name = map[int32]string{
		0: "CUSTOM_FIELD_DATA_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "NUMBER",
		3: "TOGGLE",
		4: "DROP_DOWN",
	}
	CustomFieldDataTypeEnum_CustomFieldDataType_value = map[string]int32{
		"CUSTOM_FIELD_DATA_TYPE_UNSPECIFIED": 0,
		"STRING":                             1,
		"NUMBER":                             2,
		"TOGGLE":                             3,
		"DROP_DOWN":                          4,
	}
)

func (x CustomFieldDataTypeEnum_CustomFieldDataType) Enum() *CustomFieldDataTypeEnum_CustomFieldDataType {
	p := new(CustomFieldDataTypeEnum_CustomFieldDataType)
	*p = x
	return p
}

func (x CustomFieldDataTypeEnum_CustomFieldDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomFieldDataTypeEnum_CustomFieldDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[0].Descriptor()
}

func (CustomFieldDataTypeEnum_CustomFieldDataType) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[0]
}

func (x CustomFieldDataTypeEnum_CustomFieldDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomFieldDataTypeEnum_CustomFieldDataType.Descriptor instead.
func (CustomFieldDataTypeEnum_CustomFieldDataType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{0, 0}
}

// The types of entities that a CustomField can be applied to.
type CustomFieldEntityTypeEnum_CustomFieldEntityType int32

const (
	// No value specified
	CustomFieldEntityTypeEnum_CUSTOM_FIELD_ENTITY_TYPE_UNSPECIFIED CustomFieldEntityTypeEnum_CustomFieldEntityType = 0
	// The CustomField is applied to LineItems.
	CustomFieldEntityTypeEnum_LINE_ITEM CustomFieldEntityTypeEnum_CustomFieldEntityType = 1
	// The CustomField is applied to Orders.
	CustomFieldEntityTypeEnum_ORDER CustomFieldEntityTypeEnum_CustomFieldEntityType = 2
	// The CustomField is applied to Creatives.
	CustomFieldEntityTypeEnum_CREATIVE CustomFieldEntityTypeEnum_CustomFieldEntityType = 3
	// The CustomField is applied to Proposals.
	CustomFieldEntityTypeEnum_PROPOSAL CustomFieldEntityTypeEnum_CustomFieldEntityType = 4
	// The CustomField is applied to ProposalLineItems.
	CustomFieldEntityTypeEnum_PROPOSAL_LINE_ITEM CustomFieldEntityTypeEnum_CustomFieldEntityType = 5
)

// Enum value maps for CustomFieldEntityTypeEnum_CustomFieldEntityType.
var (
	CustomFieldEntityTypeEnum_CustomFieldEntityType_name = map[int32]string{
		0: "CUSTOM_FIELD_ENTITY_TYPE_UNSPECIFIED",
		1: "LINE_ITEM",
		2: "ORDER",
		3: "CREATIVE",
		4: "PROPOSAL",
		5: "PROPOSAL_LINE_ITEM",
	}
	CustomFieldEntityTypeEnum_CustomFieldEntityType_value = map[string]int32{
		"CUSTOM_FIELD_ENTITY_TYPE_UNSPECIFIED": 0,
		"LINE_ITEM":                            1,
		"ORDER":                                2,
		"CREATIVE":                             3,
		"PROPOSAL":                             4,
		"PROPOSAL_LINE_ITEM":                   5,
	}
)

func (x CustomFieldEntityTypeEnum_CustomFieldEntityType) Enum() *CustomFieldEntityTypeEnum_CustomFieldEntityType {
	p := new(CustomFieldEntityTypeEnum_CustomFieldEntityType)
	*p = x
	return p
}

func (x CustomFieldEntityTypeEnum_CustomFieldEntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomFieldEntityTypeEnum_CustomFieldEntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[1].Descriptor()
}

func (CustomFieldEntityTypeEnum_CustomFieldEntityType) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[1]
}

func (x CustomFieldEntityTypeEnum_CustomFieldEntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomFieldEntityTypeEnum_CustomFieldEntityType.Descriptor instead.
func (CustomFieldEntityTypeEnum_CustomFieldEntityType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{1, 0}
}

// The status of the CustomField.
type CustomFieldStatusEnum_CustomFieldStatus int32

const (
	// No value specified
	CustomFieldStatusEnum_CUSTOM_FIELD_STATUS_UNSPECIFIED CustomFieldStatusEnum_CustomFieldStatus = 0
	// The CustomField is active.
	CustomFieldStatusEnum_ACTIVE CustomFieldStatusEnum_CustomFieldStatus = 1
	// The CustomField is inactive.
	CustomFieldStatusEnum_INACTIVE CustomFieldStatusEnum_CustomFieldStatus = 2
)

// Enum value maps for CustomFieldStatusEnum_CustomFieldStatus.
var (
	CustomFieldStatusEnum_CustomFieldStatus_name = map[int32]string{
		0: "CUSTOM_FIELD_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
	}
	CustomFieldStatusEnum_CustomFieldStatus_value = map[string]int32{
		"CUSTOM_FIELD_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                          1,
		"INACTIVE":                        2,
	}
)

func (x CustomFieldStatusEnum_CustomFieldStatus) Enum() *CustomFieldStatusEnum_CustomFieldStatus {
	p := new(CustomFieldStatusEnum_CustomFieldStatus)
	*p = x
	return p
}

func (x CustomFieldStatusEnum_CustomFieldStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomFieldStatusEnum_CustomFieldStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[2].Descriptor()
}

func (CustomFieldStatusEnum_CustomFieldStatus) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[2]
}

func (x CustomFieldStatusEnum_CustomFieldStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomFieldStatusEnum_CustomFieldStatus.Descriptor instead.
func (CustomFieldStatusEnum_CustomFieldStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{2, 0}
}

// The visibility level of a CustomField.
type CustomFieldVisibilityEnum_CustomFieldVisibility int32

const (
	// No value specified
	CustomFieldVisibilityEnum_CUSTOM_FIELD_VISIBILITY_UNSPECIFIED CustomFieldVisibilityEnum_CustomFieldVisibility = 0
	// The CustomField is not visible in the UI and only visible through the
	// API.
	CustomFieldVisibilityEnum_HIDDEN CustomFieldVisibilityEnum_CustomFieldVisibility = 1
	// The CustomField is visible in the UI and only editable through the API.
	CustomFieldVisibilityEnum_READ_ONLY CustomFieldVisibilityEnum_CustomFieldVisibility = 2
	// The CustomField is visible and editable in both the API and UI.
	CustomFieldVisibilityEnum_EDITABLE CustomFieldVisibilityEnum_CustomFieldVisibility = 3
)

// Enum value maps for CustomFieldVisibilityEnum_CustomFieldVisibility.
var (
	CustomFieldVisibilityEnum_CustomFieldVisibility_name = map[int32]string{
		0: "CUSTOM_FIELD_VISIBILITY_UNSPECIFIED",
		1: "HIDDEN",
		2: "READ_ONLY",
		3: "EDITABLE",
	}
	CustomFieldVisibilityEnum_CustomFieldVisibility_value = map[string]int32{
		"CUSTOM_FIELD_VISIBILITY_UNSPECIFIED": 0,
		"HIDDEN":                              1,
		"READ_ONLY":                           2,
		"EDITABLE":                            3,
	}
)

func (x CustomFieldVisibilityEnum_CustomFieldVisibility) Enum() *CustomFieldVisibilityEnum_CustomFieldVisibility {
	p := new(CustomFieldVisibilityEnum_CustomFieldVisibility)
	*p = x
	return p
}

func (x CustomFieldVisibilityEnum_CustomFieldVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomFieldVisibilityEnum_CustomFieldVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[3].Descriptor()
}

func (CustomFieldVisibilityEnum_CustomFieldVisibility) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes[3]
}

func (x CustomFieldVisibilityEnum_CustomFieldVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomFieldVisibilityEnum_CustomFieldVisibility.Descriptor instead.
func (CustomFieldVisibilityEnum_CustomFieldVisibility) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{3, 0}
}

// Wrapper message for
// [CustomFieldDataType][google.ads.admanager.v1.CustomFieldDataTypeEnum.CustomFieldDataType]
type CustomFieldDataTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomFieldDataTypeEnum) Reset() {
	*x = CustomFieldDataTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldDataTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldDataTypeEnum) ProtoMessage() {}

func (x *CustomFieldDataTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldDataTypeEnum.ProtoReflect.Descriptor instead.
func (*CustomFieldDataTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{0}
}

// Wrapper message for
// [CustomFieldEntityType][google.ads.admanager.v1.CustomFieldEntityTypeEnum.CustomFieldEntityType]
type CustomFieldEntityTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomFieldEntityTypeEnum) Reset() {
	*x = CustomFieldEntityTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldEntityTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldEntityTypeEnum) ProtoMessage() {}

func (x *CustomFieldEntityTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldEntityTypeEnum.ProtoReflect.Descriptor instead.
func (*CustomFieldEntityTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{1}
}

// Wrapper message for
// [CustomFieldStatus][google.ads.admanager.v1.CustomFieldStatusEnum.CustomFieldStatus]
type CustomFieldStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomFieldStatusEnum) Reset() {
	*x = CustomFieldStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldStatusEnum) ProtoMessage() {}

func (x *CustomFieldStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldStatusEnum.ProtoReflect.Descriptor instead.
func (*CustomFieldStatusEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{2}
}

// Wrapper message for
// [CustomFieldVisibility][google.ads.admanager.v1.CustomFieldVisibilityEnum.CustomFieldVisibility]
type CustomFieldVisibilityEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomFieldVisibilityEnum) Reset() {
	*x = CustomFieldVisibilityEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldVisibilityEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldVisibilityEnum) ProtoMessage() {}

func (x *CustomFieldVisibilityEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldVisibilityEnum.ProtoReflect.Descriptor instead.
func (*CustomFieldVisibilityEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP(), []int{3}
}

var File_google_ads_admanager_v1_custom_field_enums_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_custom_field_enums_proto_rawDesc = []byte{
	0x0a, 0x30, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61,
	0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x01, 0x0a, 0x17,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x70, 0x0a, 0x13, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26,
	0x0a, 0x22, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x54, 0x4f, 0x47, 0x47, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x52,
	0x4f, 0x50, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x22, 0xad, 0x01, 0x0a, 0x19, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x28, 0x0a, 0x24, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x46, 0x49, 0x45, 0x4c,
	0x44, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c,
	0x49, 0x4e, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x45, 0x41, 0x54, 0x49, 0x56,
	0x45, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x41, 0x4c, 0x10,
	0x04, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x41, 0x4c, 0x5f, 0x4c, 0x49,
	0x4e, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x05, 0x22, 0x6b, 0x0a, 0x15, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0x52, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x22, 0x86, 0x01, 0x0a, 0x19, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x45, 0x6e, 0x75, 0x6d, 0x22, 0x69, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a,
	0x23, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x56, 0x49,
	0x53, 0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x49, 0x44, 0x44, 0x45, 0x4e,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x44, 0x49, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x42,
	0xc9, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61,
	0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42,
	0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x75, 0x6d,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xaa, 0x02, 0x17, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5c, 0x41, 0x64,
	0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xea, 0x02,
	0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73, 0x3a, 0x3a, 0x41, 0x64,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_custom_field_enums_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_custom_field_enums_proto_rawDescData = file_google_ads_admanager_v1_custom_field_enums_proto_rawDesc
)

func file_google_ads_admanager_v1_custom_field_enums_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_custom_field_enums_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_custom_field_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_custom_field_enums_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_custom_field_enums_proto_rawDescData
}

var file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_admanager_v1_custom_field_enums_proto_goTypes = []any{
	(CustomFieldDataTypeEnum_CustomFieldDataType)(0),     // 0: google.ads.admanager.v1.CustomFieldDataTypeEnum.CustomFieldDataType
	(CustomFieldEntityTypeEnum_CustomFieldEntityType)(0), // 1: google.ads.admanager.v1.CustomFieldEntityTypeEnum.CustomFieldEntityType
	(CustomFieldStatusEnum_CustomFieldStatus)(0),         // 2: google.ads.admanager.v1.CustomFieldStatusEnum.CustomFieldStatus
	(CustomFieldVisibilityEnum_CustomFieldVisibility)(0), // 3: google.ads.admanager.v1.CustomFieldVisibilityEnum.CustomFieldVisibility
	(*CustomFieldDataTypeEnum)(nil),                      // 4: google.ads.admanager.v1.CustomFieldDataTypeEnum
	(*CustomFieldEntityTypeEnum)(nil),                    // 5: google.ads.admanager.v1.CustomFieldEntityTypeEnum
	(*CustomFieldStatusEnum)(nil),                        // 6: google.ads.admanager.v1.CustomFieldStatusEnum
	(*CustomFieldVisibilityEnum)(nil),                    // 7: google.ads.admanager.v1.CustomFieldVisibilityEnum
}
var file_google_ads_admanager_v1_custom_field_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_custom_field_enums_proto_init() }
func file_google_ads_admanager_v1_custom_field_enums_proto_init() {
	if File_google_ads_admanager_v1_custom_field_enums_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldDataTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldEntityTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CustomFieldVisibilityEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_custom_field_enums_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_admanager_v1_custom_field_enums_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_custom_field_enums_proto_depIdxs,
		EnumInfos:         file_google_ads_admanager_v1_custom_field_enums_proto_enumTypes,
		MessageInfos:      file_google_ads_admanager_v1_custom_field_enums_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_custom_field_enums_proto = out.File
	file_google_ads_admanager_v1_custom_field_enums_proto_rawDesc = nil
	file_google_ads_admanager_v1_custom_field_enums_proto_goTypes = nil
	file_google_ads_admanager_v1_custom_field_enums_proto_depIdxs = nil
}
