// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/ads/admanager/v1/order_enums.proto

package admanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The status of an Order.
type OrderStatusEnum_OrderStatus int32

const (
	// Default value. This value is unused.
	OrderStatusEnum_ORDER_STATUS_UNSPECIFIED OrderStatusEnum_OrderStatus = 0
	// Indicates that the Order has just been created but no approval has been
	// requested yet.
	OrderStatusEnum_DRAFT OrderStatusEnum_OrderStatus = 2
	// Indicates that a request for approval for the Order has been made.
	OrderStatusEnum_PENDING_APPROVAL OrderStatusEnum_OrderStatus = 3
	// Indicates that the Order has been approved and is ready to serve.
	OrderStatusEnum_APPROVED OrderStatusEnum_OrderStatus = 4
	// Indicates that the Order has been disapproved and is not eligible to
	// serve.
	OrderStatusEnum_DISAPPROVED OrderStatusEnum_OrderStatus = 5
	// This is a legacy state. Paused status should be checked on LineItems
	// within the order.
	OrderStatusEnum_PAUSED OrderStatusEnum_OrderStatus = 6
	// Indicates that the Order has been canceled and cannot serve.
	OrderStatusEnum_CANCELED OrderStatusEnum_OrderStatus = 7
	// Indicates that the Order has been deleted.
	OrderStatusEnum_DELETED OrderStatusEnum_OrderStatus = 8
)

// Enum value maps for OrderStatusEnum_OrderStatus.
var (
	OrderStatusEnum_OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		2: "DRAFT",
		3: "PENDING_APPROVAL",
		4: "APPROVED",
		5: "DISAPPROVED",
		6: "PAUSED",
		7: "CANCELED",
		8: "DELETED",
	}
	OrderStatusEnum_OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"DRAFT":                    2,
		"PENDING_APPROVAL":         3,
		"APPROVED":                 4,
		"DISAPPROVED":              5,
		"PAUSED":                   6,
		"CANCELED":                 7,
		"DELETED":                  8,
	}
)

func (x OrderStatusEnum_OrderStatus) Enum() *OrderStatusEnum_OrderStatus {
	p := new(OrderStatusEnum_OrderStatus)
	*p = x
	return p
}

func (x OrderStatusEnum_OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatusEnum_OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_admanager_v1_order_enums_proto_enumTypes[0].Descriptor()
}

func (OrderStatusEnum_OrderStatus) Type() protoreflect.EnumType {
	return &file_google_ads_admanager_v1_order_enums_proto_enumTypes[0]
}

func (x OrderStatusEnum_OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatusEnum_OrderStatus.Descriptor instead.
func (OrderStatusEnum_OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_order_enums_proto_rawDescGZIP(), []int{0, 0}
}

// Wrapper message for
// [OrderStatus][google.ads.admanager.v1.OrderStatusEnum.OrderStatus].
type OrderStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderStatusEnum) Reset() {
	*x = OrderStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_ads_admanager_v1_order_enums_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusEnum) ProtoMessage() {}

func (x *OrderStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_admanager_v1_order_enums_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusEnum.ProtoReflect.Descriptor instead.
func (*OrderStatusEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_admanager_v1_order_enums_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_admanager_v1_order_enums_proto protoreflect.FileDescriptor

var file_google_ads_admanager_v1_order_enums_proto_rawDesc = []byte{
	0x0a, 0x29, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x22, 0xa6, 0x01, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10,
	0x02, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x50, 0x50,
	0x52, 0x4f, 0x56, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x52, 0x4f,
	0x56, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x49, 0x53, 0x41, 0x50, 0x50, 0x52,
	0x4f, 0x56, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x55, 0x53, 0x45, 0x44,
	0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x07,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x08, 0x42, 0xc3, 0x01,
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73,
	0x2e, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x40, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0xaa, 0x02, 0x17, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x73, 0x2e,
	0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x17, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5c, 0x41, 0x64, 0x73, 0x5c, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xea, 0x02, 0x1a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x3a,
	0x3a, 0x41, 0x64, 0x73, 0x3a, 0x3a, 0x41, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_ads_admanager_v1_order_enums_proto_rawDescOnce sync.Once
	file_google_ads_admanager_v1_order_enums_proto_rawDescData = file_google_ads_admanager_v1_order_enums_proto_rawDesc
)

func file_google_ads_admanager_v1_order_enums_proto_rawDescGZIP() []byte {
	file_google_ads_admanager_v1_order_enums_proto_rawDescOnce.Do(func() {
		file_google_ads_admanager_v1_order_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_ads_admanager_v1_order_enums_proto_rawDescData)
	})
	return file_google_ads_admanager_v1_order_enums_proto_rawDescData
}

var file_google_ads_admanager_v1_order_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_admanager_v1_order_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_admanager_v1_order_enums_proto_goTypes = []any{
	(OrderStatusEnum_OrderStatus)(0), // 0: google.ads.admanager.v1.OrderStatusEnum.OrderStatus
	(*OrderStatusEnum)(nil),          // 1: google.ads.admanager.v1.OrderStatusEnum
}
var file_google_ads_admanager_v1_order_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_admanager_v1_order_enums_proto_init() }
func file_google_ads_admanager_v1_order_enums_proto_init() {
	if File_google_ads_admanager_v1_order_enums_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_ads_admanager_v1_order_enums_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OrderStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_ads_admanager_v1_order_enums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_admanager_v1_order_enums_proto_goTypes,
		DependencyIndexes: file_google_ads_admanager_v1_order_enums_proto_depIdxs,
		EnumInfos:         file_google_ads_admanager_v1_order_enums_proto_enumTypes,
		MessageInfos:      file_google_ads_admanager_v1_order_enums_proto_msgTypes,
	}.Build()
	File_google_ads_admanager_v1_order_enums_proto = out.File
	file_google_ads_admanager_v1_order_enums_proto_rawDesc = nil
	file_google_ads_admanager_v1_order_enums_proto_goTypes = nil
	file_google_ads_admanager_v1_order_enums_proto_depIdxs = nil
}
