// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package admob

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"

	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	httptransport "google.golang.org/api/transport/http"
	admobpb "google.golang.org/genproto/googleapis/ads/admob/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var newAdMobApiClientHook clientHook

// AdMobApiCallOptions contains the retry settings for each method of AdMobApiClient.
type AdMobApiCallOptions struct {
	GetPublisherAccount     []gax.CallOption
	ListPublisherAccounts   []gax.CallOption
	GenerateNetworkReport   []gax.CallOption
	GenerateMediationReport []gax.CallOption
}

func defaultAdMobApiRESTCallOptions() *AdMobApiCallOptions {
	return &AdMobApiCallOptions{
		GetPublisherAccount:     []gax.CallOption{},
		ListPublisherAccounts:   []gax.CallOption{},
		GenerateNetworkReport:   []gax.CallOption{},
		GenerateMediationReport: []gax.CallOption{},
	}
}

// internalAdMobApiClient is an interface that defines the methods available from AdMob API.
type internalAdMobApiClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	GetPublisherAccount(context.Context, *admobpb.GetPublisherAccountRequest, ...gax.CallOption) (*admobpb.PublisherAccount, error)
	ListPublisherAccounts(context.Context, *admobpb.ListPublisherAccountsRequest, ...gax.CallOption) *PublisherAccountIterator
	GenerateNetworkReport(context.Context, *admobpb.GenerateNetworkReportRequest, ...gax.CallOption) (admobpb.AdMobApi_GenerateNetworkReportClient, error)
	GenerateMediationReport(context.Context, *admobpb.GenerateMediationReportRequest, ...gax.CallOption) (admobpb.AdMobApi_GenerateMediationReportClient, error)
}

// AdMobApiClient is a client for interacting with AdMob API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// The AdMob API allows AdMob publishers programmatically get information about
// their AdMob account.
type AdMobApiClient struct {
	// The internal transport-dependent client.
	internalClient internalAdMobApiClient

	// The call options for this service.
	CallOptions *AdMobApiCallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *AdMobApiClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *AdMobApiClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *AdMobApiClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// GetPublisherAccount gets information about the specified AdMob publisher account.
func (c *AdMobApiClient) GetPublisherAccount(ctx context.Context, req *admobpb.GetPublisherAccountRequest, opts ...gax.CallOption) (*admobpb.PublisherAccount, error) {
	return c.internalClient.GetPublisherAccount(ctx, req, opts...)
}

// ListPublisherAccounts lists the AdMob publisher account accessible with the client credential.
// Currently, all credentials have access to at most one AdMob account.
func (c *AdMobApiClient) ListPublisherAccounts(ctx context.Context, req *admobpb.ListPublisherAccountsRequest, opts ...gax.CallOption) *PublisherAccountIterator {
	return c.internalClient.ListPublisherAccounts(ctx, req, opts...)
}

// GenerateNetworkReport generates an AdMob Network report based on the provided report
// specification.
func (c *AdMobApiClient) GenerateNetworkReport(ctx context.Context, req *admobpb.GenerateNetworkReportRequest, opts ...gax.CallOption) (admobpb.AdMobApi_GenerateNetworkReportClient, error) {
	return c.internalClient.GenerateNetworkReport(ctx, req, opts...)
}

// GenerateMediationReport generates an AdMob Mediation report based on the provided report
// specification.
func (c *AdMobApiClient) GenerateMediationReport(ctx context.Context, req *admobpb.GenerateMediationReportRequest, opts ...gax.CallOption) (admobpb.AdMobApi_GenerateMediationReportClient, error) {
	return c.internalClient.GenerateMediationReport(ctx, req, opts...)
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type adMobApiRESTClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// The x-goog-* headers to be sent with each request.
	xGoogHeaders []string

	// Points back to the CallOptions field of the containing AdMobApiClient
	CallOptions **AdMobApiCallOptions
}

// NewAdMobApiRESTClient creates a new ad mob api rest client.
//
// The AdMob API allows AdMob publishers programmatically get information about
// their AdMob account.
func NewAdMobApiRESTClient(ctx context.Context, opts ...option.ClientOption) (*AdMobApiClient, error) {
	clientOpts := append(defaultAdMobApiRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultAdMobApiRESTCallOptions()
	c := &adMobApiRESTClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	return &AdMobApiClient{internalClient: c, CallOptions: callOpts}, nil
}

func defaultAdMobApiRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://admob.googleapis.com"),
		internaloption.WithDefaultEndpointTemplate("https://admob.UNIVERSE_DOMAIN"),
		internaloption.WithDefaultMTLSEndpoint("https://admob.mtls.googleapis.com"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://admob.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableNewAuthLibrary(),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *adMobApiRESTClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *adMobApiRESTClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *adMobApiRESTClient) Connection() *grpc.ClientConn {
	return nil
}

// GetPublisherAccount gets information about the specified AdMob publisher account.
func (c *adMobApiRESTClient) GetPublisherAccount(ctx context.Context, req *admobpb.GetPublisherAccountRequest, opts ...gax.CallOption) (*admobpb.PublisherAccount, error) {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v", req.GetName())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).GetPublisherAccount[0:len((*c.CallOptions).GetPublisherAccount):len((*c.CallOptions).GetPublisherAccount)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admobpb.PublisherAccount{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// ListPublisherAccounts lists the AdMob publisher account accessible with the client credential.
// Currently, all credentials have access to at most one AdMob account.
func (c *adMobApiRESTClient) ListPublisherAccounts(ctx context.Context, req *admobpb.ListPublisherAccountsRequest, opts ...gax.CallOption) *PublisherAccountIterator {
	it := &PublisherAccountIterator{}
	req = proto.Clone(req).(*admobpb.ListPublisherAccountsRequest)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	it.InternalFetch = func(pageSize int, pageToken string) ([]*admobpb.PublisherAccount, string, error) {
		resp := &admobpb.ListPublisherAccountsResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		baseUrl, err := url.Parse(c.endpoint)
		if err != nil {
			return nil, "", err
		}
		baseUrl.Path += fmt.Sprintf("/v1/accounts")

		params := url.Values{}
		params.Add("$alt", "json;enum-encoding=int")
		if req.GetPageSize() != 0 {
			params.Add("pageSize", fmt.Sprintf("%v", req.GetPageSize()))
		}
		if req.GetPageToken() != "" {
			params.Add("pageToken", fmt.Sprintf("%v", req.GetPageToken()))
		}

		baseUrl.RawQuery = params.Encode()

		// Build HTTP headers from client and context metadata.
		hds := append(c.xGoogHeaders, "Content-Type", "application/json")
		headers := gax.BuildHeaders(ctx, hds...)
		e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			if settings.Path != "" {
				baseUrl.Path = settings.Path
			}
			httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
			if err != nil {
				return err
			}
			httpReq.Header = headers

			httpRsp, err := c.httpClient.Do(httpReq)
			if err != nil {
				return err
			}
			defer httpRsp.Body.Close()

			if err = googleapi.CheckResponse(httpRsp); err != nil {
				return err
			}

			buf, err := io.ReadAll(httpRsp.Body)
			if err != nil {
				return err
			}

			if err := unm.Unmarshal(buf, resp); err != nil {
				return err
			}

			return nil
		}, opts...)
		if e != nil {
			return nil, "", e
		}
		it.Response = resp
		return resp.GetAccount(), resp.GetNextPageToken(), nil
	}

	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

// GenerateNetworkReport generates an AdMob Network report based on the provided report
// specification.
func (c *adMobApiRESTClient) GenerateNetworkReport(ctx context.Context, req *admobpb.GenerateNetworkReportRequest, opts ...gax.CallOption) (admobpb.AdMobApi_GenerateNetworkReportClient, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v/networkReport:generate", req.GetParent())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	var streamClient *generateNetworkReportRESTClient
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		streamClient = &generateNetworkReportRESTClient{
			ctx:    ctx,
			md:     metadata.MD(httpRsp.Header),
			stream: gax.NewProtoJSONStreamReader(httpRsp.Body, (&admobpb.GenerateNetworkReportResponse{}).ProtoReflect().Type()),
		}
		return nil
	}, opts...)

	return streamClient, e
}

// generateNetworkReportRESTClient is the stream client used to consume the server stream created by
// the REST implementation of GenerateNetworkReport.
type generateNetworkReportRESTClient struct {
	ctx    context.Context
	md     metadata.MD
	stream *gax.ProtoJSONStream
}

func (c *generateNetworkReportRESTClient) Recv() (*admobpb.GenerateNetworkReportResponse, error) {
	if err := c.ctx.Err(); err != nil {
		defer c.stream.Close()
		return nil, err
	}
	msg, err := c.stream.Recv()
	if err != nil {
		defer c.stream.Close()
		return nil, err
	}
	res := msg.(*admobpb.GenerateNetworkReportResponse)
	return res, nil
}

func (c *generateNetworkReportRESTClient) Header() (metadata.MD, error) {
	return c.md, nil
}

func (c *generateNetworkReportRESTClient) Trailer() metadata.MD {
	return c.md
}

func (c *generateNetworkReportRESTClient) CloseSend() error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented for a server-stream")
}

func (c *generateNetworkReportRESTClient) Context() context.Context {
	return c.ctx
}

func (c *generateNetworkReportRESTClient) SendMsg(m interface{}) error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented for a server-stream")
}

func (c *generateNetworkReportRESTClient) RecvMsg(m interface{}) error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented, use Recv")
}

// GenerateMediationReport generates an AdMob Mediation report based on the provided report
// specification.
func (c *adMobApiRESTClient) GenerateMediationReport(ctx context.Context, req *admobpb.GenerateMediationReportRequest, opts ...gax.CallOption) (admobpb.AdMobApi_GenerateMediationReportClient, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v/mediationReport:generate", req.GetParent())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	var streamClient *generateMediationReportRESTClient
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		streamClient = &generateMediationReportRESTClient{
			ctx:    ctx,
			md:     metadata.MD(httpRsp.Header),
			stream: gax.NewProtoJSONStreamReader(httpRsp.Body, (&admobpb.GenerateMediationReportResponse{}).ProtoReflect().Type()),
		}
		return nil
	}, opts...)

	return streamClient, e
}

// generateMediationReportRESTClient is the stream client used to consume the server stream created by
// the REST implementation of GenerateMediationReport.
type generateMediationReportRESTClient struct {
	ctx    context.Context
	md     metadata.MD
	stream *gax.ProtoJSONStream
}

func (c *generateMediationReportRESTClient) Recv() (*admobpb.GenerateMediationReportResponse, error) {
	if err := c.ctx.Err(); err != nil {
		defer c.stream.Close()
		return nil, err
	}
	msg, err := c.stream.Recv()
	if err != nil {
		defer c.stream.Close()
		return nil, err
	}
	res := msg.(*admobpb.GenerateMediationReportResponse)
	return res, nil
}

func (c *generateMediationReportRESTClient) Header() (metadata.MD, error) {
	return c.md, nil
}

func (c *generateMediationReportRESTClient) Trailer() metadata.MD {
	return c.md
}

func (c *generateMediationReportRESTClient) CloseSend() error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented for a server-stream")
}

func (c *generateMediationReportRESTClient) Context() context.Context {
	return c.ctx
}

func (c *generateMediationReportRESTClient) SendMsg(m interface{}) error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented for a server-stream")
}

func (c *generateMediationReportRESTClient) RecvMsg(m interface{}) error {
	// This is a no-op to fulfill the interface.
	return errors.New("this method is not implemented, use Recv")
}
