// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package uidetection

import (
	"context"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"time"

	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	httptransport "google.golang.org/api/transport/http"
	uidetectionpb "google.golang.org/genproto/googleapis/chromeos/uidetection/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/protobuf/encoding/protojson"
)

var newClientHook clientHook

// CallOptions contains the retry settings for each method of Client.
type CallOptions struct {
	ExecuteDetection []gax.CallOption
}

func defaultGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("chromeosuidetection.googleapis.com:443"),
		internaloption.WithDefaultEndpointTemplate("chromeosuidetection.UNIVERSE_DOMAIN:443"),
		internaloption.WithDefaultMTLSEndpoint("chromeosuidetection.mtls.googleapis.com:443"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://chromeosuidetection.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultCallOptions() *CallOptions {
	return &CallOptions{
		ExecuteDetection: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
				}, gax.Backoff{
					Initial:    1000 * time.Millisecond,
					Max:        10000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
	}
}

func defaultRESTCallOptions() *CallOptions {
	return &CallOptions{
		ExecuteDetection: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnHTTPCodes(gax.Backoff{
					Initial:    1000 * time.Millisecond,
					Max:        10000 * time.Millisecond,
					Multiplier: 1.30,
				},
					http.StatusServiceUnavailable)
			}),
		},
	}
}

// internalClient is an interface that defines the methods available from ChromeOS UI Detection API.
type internalClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	ExecuteDetection(context.Context, *uidetectionpb.UiDetectionRequest, ...gax.CallOption) (*uidetectionpb.UiDetectionResponse, error)
}

// Client is a client for interacting with ChromeOS UI Detection API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// Provides image-based UI detection service.
type Client struct {
	// The internal transport-dependent client.
	internalClient internalClient

	// The call options for this service.
	CallOptions *CallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *Client) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *Client) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *Client) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// ExecuteDetection runs the detection.
func (c *Client) ExecuteDetection(ctx context.Context, req *uidetectionpb.UiDetectionRequest, opts ...gax.CallOption) (*uidetectionpb.UiDetectionResponse, error) {
	return c.internalClient.ExecuteDetection(ctx, req, opts...)
}

// gRPCClient is a client for interacting with ChromeOS UI Detection API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type gRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing Client
	CallOptions **CallOptions

	// The gRPC API client.
	client uidetectionpb.UiDetectionServiceClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string
}

// NewClient creates a new ui detection service client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// Provides image-based UI detection service.
func NewClient(ctx context.Context, opts ...option.ClientOption) (*Client, error) {
	clientOpts := defaultGRPCClientOptions()
	if newClientHook != nil {
		hookOpts, err := newClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := Client{CallOptions: defaultCallOptions()}

	c := &gRPCClient{
		connPool:    connPool,
		client:      uidetectionpb.NewUiDetectionServiceClient(connPool),
		CallOptions: &client.CallOptions,
	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *gRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *gRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *gRPCClient) Close() error {
	return c.connPool.Close()
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type restClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// The x-goog-* headers to be sent with each request.
	xGoogHeaders []string

	// Points back to the CallOptions field of the containing Client
	CallOptions **CallOptions
}

// NewRESTClient creates a new ui detection service rest client.
//
// Provides image-based UI detection service.
func NewRESTClient(ctx context.Context, opts ...option.ClientOption) (*Client, error) {
	clientOpts := append(defaultRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultRESTCallOptions()
	c := &restClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	return &Client{internalClient: c, CallOptions: callOpts}, nil
}

func defaultRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://chromeosuidetection.googleapis.com"),
		internaloption.WithDefaultEndpointTemplate("https://chromeosuidetection.UNIVERSE_DOMAIN"),
		internaloption.WithDefaultMTLSEndpoint("https://chromeosuidetection.mtls.googleapis.com"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://chromeosuidetection.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableNewAuthLibrary(),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *restClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *restClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *restClient) Connection() *grpc.ClientConn {
	return nil
}
func (c *gRPCClient) ExecuteDetection(ctx context.Context, req *uidetectionpb.UiDetectionRequest, opts ...gax.CallOption) (*uidetectionpb.UiDetectionResponse, error) {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).ExecuteDetection[0:len((*c.CallOptions).ExecuteDetection):len((*c.CallOptions).ExecuteDetection)], opts...)
	var resp *uidetectionpb.UiDetectionResponse
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.client.ExecuteDetection(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// ExecuteDetection runs the detection.
func (c *restClient) ExecuteDetection(ctx context.Context, req *uidetectionpb.UiDetectionRequest, opts ...gax.CallOption) (*uidetectionpb.UiDetectionResponse, error) {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/executeDetection:execute")

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")
	if req.GetForceImageResizing() {
		params.Add("forceImageResizing", fmt.Sprintf("%v", req.GetForceImageResizing()))
	}
	if req.GetImagePng() != nil {
		params.Add("imagePng", fmt.Sprintf("%v", req.GetImagePng()))
	}
	if req.GetRequest().GetCustomIconDetectionRequest().GetIconPng() != nil {
		params.Add("request.customIconDetectionRequest.iconPng", fmt.Sprintf("%v", req.GetRequest().GetCustomIconDetectionRequest().GetIconPng()))
	}
	if req.GetRequest().GetCustomIconDetectionRequest().GetMatchCount() != 0 {
		params.Add("request.customIconDetectionRequest.matchCount", fmt.Sprintf("%v", req.GetRequest().GetCustomIconDetectionRequest().GetMatchCount()))
	}
	if req.GetRequest().GetCustomIconDetectionRequest().GetMinConfidenceThreshold() != 0 {
		params.Add("request.customIconDetectionRequest.minConfidenceThreshold", fmt.Sprintf("%v", req.GetRequest().GetCustomIconDetectionRequest().GetMinConfidenceThreshold()))
	}
	if req.GetRequest().GetTextBlockDetectionRequest().GetDisableApproxMatch() {
		params.Add("request.textBlockDetectionRequest.disableApproxMatch", fmt.Sprintf("%v", req.GetRequest().GetTextBlockDetectionRequest().GetDisableApproxMatch()))
	}
	if req.GetRequest().GetTextBlockDetectionRequest() != nil && req.GetRequest().GetTextBlockDetectionRequest().MaxEditDistance != nil {
		params.Add("request.textBlockDetectionRequest.maxEditDistance", fmt.Sprintf("%v", req.GetRequest().GetTextBlockDetectionRequest().GetMaxEditDistance()))
	}
	if req.GetRequest().GetTextBlockDetectionRequest().GetRegexMode() {
		params.Add("request.textBlockDetectionRequest.regexMode", fmt.Sprintf("%v", req.GetRequest().GetTextBlockDetectionRequest().GetRegexMode()))
	}
	if req.GetRequest().GetTextBlockDetectionRequest().GetSpecifiedWordsOnly() {
		params.Add("request.textBlockDetectionRequest.specifiedWordsOnly", fmt.Sprintf("%v", req.GetRequest().GetTextBlockDetectionRequest().GetSpecifiedWordsOnly()))
	}
	if items := req.GetRequest().GetTextBlockDetectionRequest().GetWords(); len(items) > 0 {
		for _, item := range items {
			params.Add("request.textBlockDetectionRequest.words", fmt.Sprintf("%v", item))
		}
	}
	if req.GetRequest().GetWordDetectionRequest().GetDisableApproxMatch() {
		params.Add("request.wordDetectionRequest.disableApproxMatch", fmt.Sprintf("%v", req.GetRequest().GetWordDetectionRequest().GetDisableApproxMatch()))
	}
	if req.GetRequest().GetWordDetectionRequest() != nil && req.GetRequest().GetWordDetectionRequest().MaxEditDistance != nil {
		params.Add("request.wordDetectionRequest.maxEditDistance", fmt.Sprintf("%v", req.GetRequest().GetWordDetectionRequest().GetMaxEditDistance()))
	}
	if req.GetRequest().GetWordDetectionRequest().GetRegexMode() {
		params.Add("request.wordDetectionRequest.regexMode", fmt.Sprintf("%v", req.GetRequest().GetWordDetectionRequest().GetRegexMode()))
	}
	params.Add("request.wordDetectionRequest.word", fmt.Sprintf("%v", req.GetRequest().GetWordDetectionRequest().GetWord()))
	if req != nil && req.ResizeImage != nil {
		params.Add("resizeImage", fmt.Sprintf("%v", req.GetResizeImage()))
	}
	if req.GetReturnTransformedImage() {
		params.Add("returnTransformedImage", fmt.Sprintf("%v", req.GetReturnTransformedImage()))
	}
	if req.GetTestId() != "" {
		params.Add("testId", fmt.Sprintf("%v", req.GetTestId()))
	}
	if req.GetTestMetadata().GetBoard() != "" {
		params.Add("testMetadata.board", fmt.Sprintf("%v", req.GetTestMetadata().GetBoard()))
	}
	if req.GetTestMetadata().GetCrosBuild() != "" {
		params.Add("testMetadata.crosBuild", fmt.Sprintf("%v", req.GetTestMetadata().GetCrosBuild()))
	}
	if req.GetTestMetadata().GetModel() != "" {
		params.Add("testMetadata.model", fmt.Sprintf("%v", req.GetTestMetadata().GetModel()))
	}
	if req.GetTestMetadata().GetTestId() != "" {
		params.Add("testMetadata.testId", fmt.Sprintf("%v", req.GetTestMetadata().GetTestId()))
	}

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := append(c.xGoogHeaders, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).ExecuteDetection[0:len((*c.CallOptions).ExecuteDetection):len((*c.CallOptions).ExecuteDetection)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &uidetectionpb.UiDetectionResponse{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
