// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/compute/logging/dr/v1/disaster_recovery_event.proto

package dr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The severity of the disaster recovery event.
type DisasterRecoveryEvent_Severity int32

const (
	// Unspecified.
	DisasterRecoveryEvent_SEVERITY_UNSPECIFIED DisasterRecoveryEvent_Severity = 0
	// The Compute Engine resource is broken. A person must take an action.
	DisasterRecoveryEvent_ACTION_REQUIRED DisasterRecoveryEvent_Severity = 1
	// The Compute Engine resource is functioning. A change was applied to the
	// resource during disaster recovery. Please take action to review
	// the change to avoid unexpected problems.
	DisasterRecoveryEvent_ACTION_SUGGESTED DisasterRecoveryEvent_Severity = 2
	// Normal maintenance opeartions during disaster recovery, such as start up,
	// shut down.
	DisasterRecoveryEvent_NOTICE DisasterRecoveryEvent_Severity = 3
)

// Enum value maps for DisasterRecoveryEvent_Severity.
var (
	DisasterRecoveryEvent_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "ACTION_REQUIRED",
		2: "ACTION_SUGGESTED",
		3: "NOTICE",
	}
	DisasterRecoveryEvent_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"ACTION_REQUIRED":      1,
		"ACTION_SUGGESTED":     2,
		"NOTICE":               3,
	}
)

func (x DisasterRecoveryEvent_Severity) Enum() *DisasterRecoveryEvent_Severity {
	p := new(DisasterRecoveryEvent_Severity)
	*p = x
	return p
}

func (x DisasterRecoveryEvent_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisasterRecoveryEvent_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_google_compute_logging_dr_v1_disaster_recovery_event_proto_enumTypes[0].Descriptor()
}

func (DisasterRecoveryEvent_Severity) Type() protoreflect.EnumType {
	return &file_google_compute_logging_dr_v1_disaster_recovery_event_proto_enumTypes[0]
}

func (x DisasterRecoveryEvent_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisasterRecoveryEvent_Severity.Descriptor instead.
func (DisasterRecoveryEvent_Severity) EnumDescriptor() ([]byte, []int) {
	return file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescGZIP(), []int{0, 0}
}

// An event signifying a Compute Engine resource is impacted by the disaster
// recovery.
type DisasterRecoveryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The severity level.
	Severity *DisasterRecoveryEvent_Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=google.compute.logging.dr.v1.DisasterRecoveryEvent_Severity,oneof" json:"severity,omitempty"`
	// Details about the impact on the Compute Engine resource, e.g. "the resource
	// is deleted during the disaster recovery".
	Details *string `protobuf:"bytes,2,opt,name=details,proto3,oneof" json:"details,omitempty"`
}

func (x *DisasterRecoveryEvent) Reset() {
	*x = DisasterRecoveryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisasterRecoveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisasterRecoveryEvent) ProtoMessage() {}

func (x *DisasterRecoveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisasterRecoveryEvent.ProtoReflect.Descriptor instead.
func (*DisasterRecoveryEvent) Descriptor() ([]byte, []int) {
	return file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescGZIP(), []int{0}
}

func (x *DisasterRecoveryEvent) GetSeverity() DisasterRecoveryEvent_Severity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return DisasterRecoveryEvent_SEVERITY_UNSPECIFIED
}

func (x *DisasterRecoveryEvent) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

var File_google_compute_logging_dr_v1_disaster_recovery_event_proto protoreflect.FileDescriptor

var file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x64,
	0x69, 0x73, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67,
	0x67, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x02, 0x0a, 0x15, 0x44,
	0x69, 0x73, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x64, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x88,
	0x01, 0x01, 0x22, 0x5b, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18,
	0x0a, 0x14, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a,
	0x10, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x47, 0x47, 0x45, 0x53, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x03, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0xe1, 0x01, 0x0a, 0x20, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e,
	0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x1a, 0x44,
	0x69, 0x73, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69,
	0x6e, 0x67, 0x2f, 0x64, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x72, 0xaa, 0x02, 0x1c, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x4c, 0x6f, 0x67,
	0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x1c, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x5c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5c, 0x4c, 0x6f, 0x67, 0x67,
	0x69, 0x6e, 0x67, 0x5c, 0x44, 0x72, 0x5c, 0x56, 0x31, 0xea, 0x02, 0x20, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x3a, 0x3a, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x3a, 0x3a, 0x4c, 0x6f, 0x67,
	0x67, 0x69, 0x6e, 0x67, 0x3a, 0x3a, 0x44, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescOnce sync.Once
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescData = file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDesc
)

func file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescGZIP() []byte {
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescOnce.Do(func() {
		file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescData)
	})
	return file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDescData
}

var file_google_compute_logging_dr_v1_disaster_recovery_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_compute_logging_dr_v1_disaster_recovery_event_proto_goTypes = []any{
	(DisasterRecoveryEvent_Severity)(0), // 0: google.compute.logging.dr.v1.DisasterRecoveryEvent.Severity
	(*DisasterRecoveryEvent)(nil),       // 1: google.compute.logging.dr.v1.DisasterRecoveryEvent
}
var file_google_compute_logging_dr_v1_disaster_recovery_event_proto_depIdxs = []int32{
	0, // 0: google.compute.logging.dr.v1.DisasterRecoveryEvent.severity:type_name -> google.compute.logging.dr.v1.DisasterRecoveryEvent.Severity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_compute_logging_dr_v1_disaster_recovery_event_proto_init() }
func file_google_compute_logging_dr_v1_disaster_recovery_event_proto_init() {
	if File_google_compute_logging_dr_v1_disaster_recovery_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DisasterRecoveryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_compute_logging_dr_v1_disaster_recovery_event_proto_goTypes,
		DependencyIndexes: file_google_compute_logging_dr_v1_disaster_recovery_event_proto_depIdxs,
		EnumInfos:         file_google_compute_logging_dr_v1_disaster_recovery_event_proto_enumTypes,
		MessageInfos:      file_google_compute_logging_dr_v1_disaster_recovery_event_proto_msgTypes,
	}.Build()
	File_google_compute_logging_dr_v1_disaster_recovery_event_proto = out.File
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_rawDesc = nil
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_goTypes = nil
	file_google_compute_logging_dr_v1_disaster_recovery_event_proto_depIdxs = nil
}
