// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package activity

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"time"

	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	httptransport "google.golang.org/api/transport/http"
	activitypb "google.golang.org/genproto/googleapis/apps/drive/activity/v2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var newDriveActivityClientHook clientHook

// DriveActivityCallOptions contains the retry settings for each method of DriveActivityClient.
type DriveActivityCallOptions struct {
	QueryDriveActivity []gax.CallOption
}

func defaultDriveActivityGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("driveactivity.googleapis.com:443"),
		internaloption.WithDefaultEndpointTemplate("driveactivity.UNIVERSE_DOMAIN:443"),
		internaloption.WithDefaultMTLSEndpoint("driveactivity.mtls.googleapis.com:443"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://driveactivity.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultDriveActivityCallOptions() *DriveActivityCallOptions {
	return &DriveActivityCallOptions{
		QueryDriveActivity: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
				}, gax.Backoff{
					Initial:    1000 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
	}
}

func defaultDriveActivityRESTCallOptions() *DriveActivityCallOptions {
	return &DriveActivityCallOptions{
		QueryDriveActivity: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnHTTPCodes(gax.Backoff{
					Initial:    1000 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				},
					http.StatusServiceUnavailable)
			}),
		},
	}
}

// internalDriveActivityClient is an interface that defines the methods available from Drive Activity API.
type internalDriveActivityClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	QueryDriveActivity(context.Context, *activitypb.QueryDriveActivityRequest, ...gax.CallOption) *DriveActivityIterator
}

// DriveActivityClient is a client for interacting with Drive Activity API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// Service for querying activity on Drive items. Activity is user
// or system action on Drive items that happened in the past. A Drive item can
// be a file or folder, or a Team Drive.
type DriveActivityClient struct {
	// The internal transport-dependent client.
	internalClient internalDriveActivityClient

	// The call options for this service.
	CallOptions *DriveActivityCallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *DriveActivityClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *DriveActivityClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *DriveActivityClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// QueryDriveActivity query past activity in Google Drive.
func (c *DriveActivityClient) QueryDriveActivity(ctx context.Context, req *activitypb.QueryDriveActivityRequest, opts ...gax.CallOption) *DriveActivityIterator {
	return c.internalClient.QueryDriveActivity(ctx, req, opts...)
}

// driveActivityGRPCClient is a client for interacting with Drive Activity API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type driveActivityGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing DriveActivityClient
	CallOptions **DriveActivityCallOptions

	// The gRPC API client.
	driveActivityClient activitypb.DriveActivityServiceClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string
}

// NewDriveActivityClient creates a new drive activity service client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// Service for querying activity on Drive items. Activity is user
// or system action on Drive items that happened in the past. A Drive item can
// be a file or folder, or a Team Drive.
func NewDriveActivityClient(ctx context.Context, opts ...option.ClientOption) (*DriveActivityClient, error) {
	clientOpts := defaultDriveActivityGRPCClientOptions()
	if newDriveActivityClientHook != nil {
		hookOpts, err := newDriveActivityClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := DriveActivityClient{CallOptions: defaultDriveActivityCallOptions()}

	c := &driveActivityGRPCClient{
		connPool:            connPool,
		driveActivityClient: activitypb.NewDriveActivityServiceClient(connPool),
		CallOptions:         &client.CallOptions,
	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *driveActivityGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *driveActivityGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *driveActivityGRPCClient) Close() error {
	return c.connPool.Close()
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type driveActivityRESTClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// The x-goog-* headers to be sent with each request.
	xGoogHeaders []string

	// Points back to the CallOptions field of the containing DriveActivityClient
	CallOptions **DriveActivityCallOptions
}

// NewDriveActivityRESTClient creates a new drive activity service rest client.
//
// Service for querying activity on Drive items. Activity is user
// or system action on Drive items that happened in the past. A Drive item can
// be a file or folder, or a Team Drive.
func NewDriveActivityRESTClient(ctx context.Context, opts ...option.ClientOption) (*DriveActivityClient, error) {
	clientOpts := append(defaultDriveActivityRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultDriveActivityRESTCallOptions()
	c := &driveActivityRESTClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	return &DriveActivityClient{internalClient: c, CallOptions: callOpts}, nil
}

func defaultDriveActivityRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://driveactivity.googleapis.com"),
		internaloption.WithDefaultEndpointTemplate("https://driveactivity.UNIVERSE_DOMAIN"),
		internaloption.WithDefaultMTLSEndpoint("https://driveactivity.mtls.googleapis.com"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://driveactivity.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableNewAuthLibrary(),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *driveActivityRESTClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *driveActivityRESTClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *driveActivityRESTClient) Connection() *grpc.ClientConn {
	return nil
}
func (c *driveActivityGRPCClient) QueryDriveActivity(ctx context.Context, req *activitypb.QueryDriveActivityRequest, opts ...gax.CallOption) *DriveActivityIterator {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).QueryDriveActivity[0:len((*c.CallOptions).QueryDriveActivity):len((*c.CallOptions).QueryDriveActivity)], opts...)
	it := &DriveActivityIterator{}
	req = proto.Clone(req).(*activitypb.QueryDriveActivityRequest)
	it.InternalFetch = func(pageSize int, pageToken string) ([]*activitypb.DriveActivity, string, error) {
		resp := &activitypb.QueryDriveActivityResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			var err error
			resp, err = c.driveActivityClient.QueryDriveActivity(ctx, req, settings.GRPC...)
			return err
		}, opts...)
		if err != nil {
			return nil, "", err
		}

		it.Response = resp
		return resp.GetActivities(), resp.GetNextPageToken(), nil
	}
	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

// QueryDriveActivity query past activity in Google Drive.
func (c *driveActivityRESTClient) QueryDriveActivity(ctx context.Context, req *activitypb.QueryDriveActivityRequest, opts ...gax.CallOption) *DriveActivityIterator {
	it := &DriveActivityIterator{}
	req = proto.Clone(req).(*activitypb.QueryDriveActivityRequest)
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	it.InternalFetch = func(pageSize int, pageToken string) ([]*activitypb.DriveActivity, string, error) {
		resp := &activitypb.QueryDriveActivityResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		jsonReq, err := m.Marshal(req)
		if err != nil {
			return nil, "", err
		}

		baseUrl, err := url.Parse(c.endpoint)
		if err != nil {
			return nil, "", err
		}
		baseUrl.Path += fmt.Sprintf("/v2/activity:query")

		params := url.Values{}
		params.Add("$alt", "json;enum-encoding=int")

		baseUrl.RawQuery = params.Encode()

		// Build HTTP headers from client and context metadata.
		hds := append(c.xGoogHeaders, "Content-Type", "application/json")
		headers := gax.BuildHeaders(ctx, hds...)
		e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			if settings.Path != "" {
				baseUrl.Path = settings.Path
			}
			httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
			if err != nil {
				return err
			}
			httpReq.Header = headers

			httpRsp, err := c.httpClient.Do(httpReq)
			if err != nil {
				return err
			}
			defer httpRsp.Body.Close()

			if err = googleapi.CheckResponse(httpRsp); err != nil {
				return err
			}

			buf, err := io.ReadAll(httpRsp.Body)
			if err != nil {
				return err
			}

			if err := unm.Unmarshal(buf, resp); err != nil {
				return err
			}

			return nil
		}, opts...)
		if e != nil {
			return nil, "", e
		}
		it.Response = resp
		return resp.GetActivities(), resp.GetNextPageToken(), nil
	}

	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}
