// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package admanager

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"

	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	httptransport "google.golang.org/api/transport/http"
	admanagerpb "google.golang.org/genproto/googleapis/ads/admanager/v1"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var newEntitySignalsMappingClientHook clientHook

// EntitySignalsMappingCallOptions contains the retry settings for each method of EntitySignalsMappingClient.
type EntitySignalsMappingCallOptions struct {
	GetEntitySignalsMapping          []gax.CallOption
	ListEntitySignalsMappings        []gax.CallOption
	CreateEntitySignalsMapping       []gax.CallOption
	UpdateEntitySignalsMapping       []gax.CallOption
	BatchCreateEntitySignalsMappings []gax.CallOption
	BatchUpdateEntitySignalsMappings []gax.CallOption
	GetOperation                     []gax.CallOption
}

func defaultEntitySignalsMappingRESTCallOptions() *EntitySignalsMappingCallOptions {
	return &EntitySignalsMappingCallOptions{
		GetEntitySignalsMapping:          []gax.CallOption{},
		ListEntitySignalsMappings:        []gax.CallOption{},
		CreateEntitySignalsMapping:       []gax.CallOption{},
		UpdateEntitySignalsMapping:       []gax.CallOption{},
		BatchCreateEntitySignalsMappings: []gax.CallOption{},
		BatchUpdateEntitySignalsMappings: []gax.CallOption{},
		GetOperation:                     []gax.CallOption{},
	}
}

// internalEntitySignalsMappingClient is an interface that defines the methods available from Google Ad Manager API.
type internalEntitySignalsMappingClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	GetEntitySignalsMapping(context.Context, *admanagerpb.GetEntitySignalsMappingRequest, ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error)
	ListEntitySignalsMappings(context.Context, *admanagerpb.ListEntitySignalsMappingsRequest, ...gax.CallOption) *EntitySignalsMappingIterator
	CreateEntitySignalsMapping(context.Context, *admanagerpb.CreateEntitySignalsMappingRequest, ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error)
	UpdateEntitySignalsMapping(context.Context, *admanagerpb.UpdateEntitySignalsMappingRequest, ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error)
	BatchCreateEntitySignalsMappings(context.Context, *admanagerpb.BatchCreateEntitySignalsMappingsRequest, ...gax.CallOption) (*admanagerpb.BatchCreateEntitySignalsMappingsResponse, error)
	BatchUpdateEntitySignalsMappings(context.Context, *admanagerpb.BatchUpdateEntitySignalsMappingsRequest, ...gax.CallOption) (*admanagerpb.BatchUpdateEntitySignalsMappingsResponse, error)
	GetOperation(context.Context, *longrunningpb.GetOperationRequest, ...gax.CallOption) (*longrunningpb.Operation, error)
}

// EntitySignalsMappingClient is a client for interacting with Google Ad Manager API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// Provides methods for handling EntitySignalsMapping objects.
type EntitySignalsMappingClient struct {
	// The internal transport-dependent client.
	internalClient internalEntitySignalsMappingClient

	// The call options for this service.
	CallOptions *EntitySignalsMappingCallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *EntitySignalsMappingClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *EntitySignalsMappingClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *EntitySignalsMappingClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// GetEntitySignalsMapping aPI to retrieve a EntitySignalsMapping object.
func (c *EntitySignalsMappingClient) GetEntitySignalsMapping(ctx context.Context, req *admanagerpb.GetEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	return c.internalClient.GetEntitySignalsMapping(ctx, req, opts...)
}

// ListEntitySignalsMappings aPI to retrieve a list of EntitySignalsMapping objects.
func (c *EntitySignalsMappingClient) ListEntitySignalsMappings(ctx context.Context, req *admanagerpb.ListEntitySignalsMappingsRequest, opts ...gax.CallOption) *EntitySignalsMappingIterator {
	return c.internalClient.ListEntitySignalsMappings(ctx, req, opts...)
}

// CreateEntitySignalsMapping aPI to create an EntitySignalsMapping object.
func (c *EntitySignalsMappingClient) CreateEntitySignalsMapping(ctx context.Context, req *admanagerpb.CreateEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	return c.internalClient.CreateEntitySignalsMapping(ctx, req, opts...)
}

// UpdateEntitySignalsMapping aPI to update an EntitySignalsMapping object.
func (c *EntitySignalsMappingClient) UpdateEntitySignalsMapping(ctx context.Context, req *admanagerpb.UpdateEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	return c.internalClient.UpdateEntitySignalsMapping(ctx, req, opts...)
}

// BatchCreateEntitySignalsMappings aPI to batch create EntitySignalsMapping objects.
func (c *EntitySignalsMappingClient) BatchCreateEntitySignalsMappings(ctx context.Context, req *admanagerpb.BatchCreateEntitySignalsMappingsRequest, opts ...gax.CallOption) (*admanagerpb.BatchCreateEntitySignalsMappingsResponse, error) {
	return c.internalClient.BatchCreateEntitySignalsMappings(ctx, req, opts...)
}

// BatchUpdateEntitySignalsMappings aPI to batch update EntitySignalsMapping objects.
func (c *EntitySignalsMappingClient) BatchUpdateEntitySignalsMappings(ctx context.Context, req *admanagerpb.BatchUpdateEntitySignalsMappingsRequest, opts ...gax.CallOption) (*admanagerpb.BatchUpdateEntitySignalsMappingsResponse, error) {
	return c.internalClient.BatchUpdateEntitySignalsMappings(ctx, req, opts...)
}

// GetOperation is a utility method from google.longrunning.Operations.
func (c *EntitySignalsMappingClient) GetOperation(ctx context.Context, req *longrunningpb.GetOperationRequest, opts ...gax.CallOption) (*longrunningpb.Operation, error) {
	return c.internalClient.GetOperation(ctx, req, opts...)
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type entitySignalsMappingRESTClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// The x-goog-* headers to be sent with each request.
	xGoogHeaders []string

	// Points back to the CallOptions field of the containing EntitySignalsMappingClient
	CallOptions **EntitySignalsMappingCallOptions
}

// NewEntitySignalsMappingRESTClient creates a new entity signals mapping service rest client.
//
// Provides methods for handling EntitySignalsMapping objects.
func NewEntitySignalsMappingRESTClient(ctx context.Context, opts ...option.ClientOption) (*EntitySignalsMappingClient, error) {
	clientOpts := append(defaultEntitySignalsMappingRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultEntitySignalsMappingRESTCallOptions()
	c := &entitySignalsMappingRESTClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	return &EntitySignalsMappingClient{internalClient: c, CallOptions: callOpts}, nil
}

func defaultEntitySignalsMappingRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://admanager.googleapis.com"),
		internaloption.WithDefaultEndpointTemplate("https://admanager.UNIVERSE_DOMAIN"),
		internaloption.WithDefaultMTLSEndpoint("https://admanager.mtls.googleapis.com"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://admanager.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableNewAuthLibrary(),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *entitySignalsMappingRESTClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *entitySignalsMappingRESTClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *entitySignalsMappingRESTClient) Connection() *grpc.ClientConn {
	return nil
}

// GetEntitySignalsMapping aPI to retrieve a EntitySignalsMapping object.
func (c *entitySignalsMappingRESTClient) GetEntitySignalsMapping(ctx context.Context, req *admanagerpb.GetEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v", req.GetName())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).GetEntitySignalsMapping[0:len((*c.CallOptions).GetEntitySignalsMapping):len((*c.CallOptions).GetEntitySignalsMapping)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admanagerpb.EntitySignalsMapping{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// ListEntitySignalsMappings aPI to retrieve a list of EntitySignalsMapping objects.
func (c *entitySignalsMappingRESTClient) ListEntitySignalsMappings(ctx context.Context, req *admanagerpb.ListEntitySignalsMappingsRequest, opts ...gax.CallOption) *EntitySignalsMappingIterator {
	it := &EntitySignalsMappingIterator{}
	req = proto.Clone(req).(*admanagerpb.ListEntitySignalsMappingsRequest)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	it.InternalFetch = func(pageSize int, pageToken string) ([]*admanagerpb.EntitySignalsMapping, string, error) {
		resp := &admanagerpb.ListEntitySignalsMappingsResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		baseUrl, err := url.Parse(c.endpoint)
		if err != nil {
			return nil, "", err
		}
		baseUrl.Path += fmt.Sprintf("/v1/%v/entitySignalsMappings", req.GetParent())

		params := url.Values{}
		params.Add("$alt", "json;enum-encoding=int")
		if req.GetFilter() != "" {
			params.Add("filter", fmt.Sprintf("%v", req.GetFilter()))
		}
		if req.GetOrderBy() != "" {
			params.Add("orderBy", fmt.Sprintf("%v", req.GetOrderBy()))
		}
		if req.GetPageSize() != 0 {
			params.Add("pageSize", fmt.Sprintf("%v", req.GetPageSize()))
		}
		if req.GetPageToken() != "" {
			params.Add("pageToken", fmt.Sprintf("%v", req.GetPageToken()))
		}
		if req.GetSkip() != 0 {
			params.Add("skip", fmt.Sprintf("%v", req.GetSkip()))
		}

		baseUrl.RawQuery = params.Encode()

		// Build HTTP headers from client and context metadata.
		hds := append(c.xGoogHeaders, "Content-Type", "application/json")
		headers := gax.BuildHeaders(ctx, hds...)
		e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			if settings.Path != "" {
				baseUrl.Path = settings.Path
			}
			httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
			if err != nil {
				return err
			}
			httpReq.Header = headers

			httpRsp, err := c.httpClient.Do(httpReq)
			if err != nil {
				return err
			}
			defer httpRsp.Body.Close()

			if err = googleapi.CheckResponse(httpRsp); err != nil {
				return err
			}

			buf, err := io.ReadAll(httpRsp.Body)
			if err != nil {
				return err
			}

			if err := unm.Unmarshal(buf, resp); err != nil {
				return err
			}

			return nil
		}, opts...)
		if e != nil {
			return nil, "", e
		}
		it.Response = resp
		return resp.GetEntitySignalsMappings(), resp.GetNextPageToken(), nil
	}

	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

// CreateEntitySignalsMapping aPI to create an EntitySignalsMapping object.
func (c *entitySignalsMappingRESTClient) CreateEntitySignalsMapping(ctx context.Context, req *admanagerpb.CreateEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	body := req.GetEntitySignalsMapping()
	jsonReq, err := m.Marshal(body)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v/entitySignalsMappings", req.GetParent())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).CreateEntitySignalsMapping[0:len((*c.CallOptions).CreateEntitySignalsMapping):len((*c.CallOptions).CreateEntitySignalsMapping)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admanagerpb.EntitySignalsMapping{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// UpdateEntitySignalsMapping aPI to update an EntitySignalsMapping object.
func (c *entitySignalsMappingRESTClient) UpdateEntitySignalsMapping(ctx context.Context, req *admanagerpb.UpdateEntitySignalsMappingRequest, opts ...gax.CallOption) (*admanagerpb.EntitySignalsMapping, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	body := req.GetEntitySignalsMapping()
	jsonReq, err := m.Marshal(body)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v", req.GetEntitySignalsMapping().GetName())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")
	if req.GetUpdateMask() != nil {
		field, err := protojson.Marshal(req.GetUpdateMask())
		if err != nil {
			return nil, err
		}
		params.Add("updateMask", string(field[1:len(field)-1]))
	}

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "entity_signals_mapping.name", url.QueryEscape(req.GetEntitySignalsMapping().GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).UpdateEntitySignalsMapping[0:len((*c.CallOptions).UpdateEntitySignalsMapping):len((*c.CallOptions).UpdateEntitySignalsMapping)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admanagerpb.EntitySignalsMapping{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("PATCH", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// BatchCreateEntitySignalsMappings aPI to batch create EntitySignalsMapping objects.
func (c *entitySignalsMappingRESTClient) BatchCreateEntitySignalsMappings(ctx context.Context, req *admanagerpb.BatchCreateEntitySignalsMappingsRequest, opts ...gax.CallOption) (*admanagerpb.BatchCreateEntitySignalsMappingsResponse, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v/entitySignalsMappings:batchCreate", req.GetParent())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).BatchCreateEntitySignalsMappings[0:len((*c.CallOptions).BatchCreateEntitySignalsMappings):len((*c.CallOptions).BatchCreateEntitySignalsMappings)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admanagerpb.BatchCreateEntitySignalsMappingsResponse{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// BatchUpdateEntitySignalsMappings aPI to batch update EntitySignalsMapping objects.
func (c *entitySignalsMappingRESTClient) BatchUpdateEntitySignalsMappings(ctx context.Context, req *admanagerpb.BatchUpdateEntitySignalsMappingsRequest, opts ...gax.CallOption) (*admanagerpb.BatchUpdateEntitySignalsMappingsResponse, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v/entitySignalsMappings:batchUpdate", req.GetParent())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).BatchUpdateEntitySignalsMappings[0:len((*c.CallOptions).BatchUpdateEntitySignalsMappings):len((*c.CallOptions).BatchUpdateEntitySignalsMappings)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &admanagerpb.BatchUpdateEntitySignalsMappingsResponse{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}

// GetOperation is a utility method from google.longrunning.Operations.
func (c *entitySignalsMappingRESTClient) GetOperation(ctx context.Context, req *longrunningpb.GetOperationRequest, opts ...gax.CallOption) (*longrunningpb.Operation, error) {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/%v", req.GetName())

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	hds = append(hds, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).GetOperation[0:len((*c.CallOptions).GetOperation):len((*c.CallOptions).GetOperation)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &longrunningpb.Operation{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
