// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: google/analytics/cloud/bigquery_export_platform_log.proto

package cloud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The status of the export.
type ExportStatusLog_Status int32

const (
	// The export status is unknown.
	ExportStatusLog_UNKNOWN ExportStatusLog_Status = 0
	// The export completed and data is complete.
	ExportStatusLog_COMPLETE ExportStatusLog_Status = 1
	// The export completed but data is incomplete.
	ExportStatusLog_INCOMPLETE ExportStatusLog_Status = 2
	// The export failed.
	ExportStatusLog_FAILED ExportStatusLog_Status = 3
)

// Enum value maps for ExportStatusLog_Status.
var (
	ExportStatusLog_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMPLETE",
		2: "INCOMPLETE",
		3: "FAILED",
	}
	ExportStatusLog_Status_value = map[string]int32{
		"UNKNOWN":    0,
		"COMPLETE":   1,
		"INCOMPLETE": 2,
		"FAILED":     3,
	}
)

func (x ExportStatusLog_Status) Enum() *ExportStatusLog_Status {
	p := new(ExportStatusLog_Status)
	*p = x
	return p
}

func (x ExportStatusLog_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportStatusLog_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_google_analytics_cloud_bigquery_export_platform_log_proto_enumTypes[0].Descriptor()
}

func (ExportStatusLog_Status) Type() protoreflect.EnumType {
	return &file_google_analytics_cloud_bigquery_export_platform_log_proto_enumTypes[0]
}

func (x ExportStatusLog_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportStatusLog_Status.Descriptor instead.
func (ExportStatusLog_Status) EnumDescriptor() ([]byte, []int) {
	return file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescGZIP(), []int{0, 0}
}

// ExportStatusLog is used in a log entry to represent the status of a given
// BigQuery export job from Google Analytics. Typically, it is sent at the
// beginning of the day to indicate the completion of the previous day's export.
type ExportStatusLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The date of the export. Usually set to the collection date (YYYYMMDD).
	ExportDate string `protobuf:"bytes,1,opt,name=export_date,json=exportDate,proto3" json:"export_date,omitempty"`
	// The status of the export.
	Status ExportStatusLog_Status `protobuf:"varint,2,opt,name=status,proto3,enum=google.analytics.cloud.ExportStatusLog_Status" json:"status,omitempty"`
	// The number of events exported, may include events not eligible for SLA.
	EventCount int64 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	// Additional information associated with the status.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ExportStatusLog) Reset() {
	*x = ExportStatusLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_analytics_cloud_bigquery_export_platform_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportStatusLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportStatusLog) ProtoMessage() {}

func (x *ExportStatusLog) ProtoReflect() protoreflect.Message {
	mi := &file_google_analytics_cloud_bigquery_export_platform_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportStatusLog.ProtoReflect.Descriptor instead.
func (*ExportStatusLog) Descriptor() ([]byte, []int) {
	return file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescGZIP(), []int{0}
}

func (x *ExportStatusLog) GetExportDate() string {
	if x != nil {
		return x.ExportDate
	}
	return ""
}

func (x *ExportStatusLog) GetStatus() ExportStatusLog_Status {
	if x != nil {
		return x.Status
	}
	return ExportStatusLog_UNKNOWN
}

func (x *ExportStatusLog) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *ExportStatusLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_google_analytics_cloud_bigquery_export_platform_log_proto protoreflect.FileDescriptor

var file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDesc = []byte{
	0x0a, 0x39, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x22, 0xf6, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x6f,
	0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x56, 0x5a, 0x3b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x3b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0xaa, 0x02, 0x16, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescOnce sync.Once
	file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescData = file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDesc
)

func file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescGZIP() []byte {
	file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescOnce.Do(func() {
		file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescData)
	})
	return file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDescData
}

var file_google_analytics_cloud_bigquery_export_platform_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_analytics_cloud_bigquery_export_platform_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_analytics_cloud_bigquery_export_platform_log_proto_goTypes = []any{
	(ExportStatusLog_Status)(0), // 0: google.analytics.cloud.ExportStatusLog.Status
	(*ExportStatusLog)(nil),     // 1: google.analytics.cloud.ExportStatusLog
}
var file_google_analytics_cloud_bigquery_export_platform_log_proto_depIdxs = []int32{
	0, // 0: google.analytics.cloud.ExportStatusLog.status:type_name -> google.analytics.cloud.ExportStatusLog.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_analytics_cloud_bigquery_export_platform_log_proto_init() }
func file_google_analytics_cloud_bigquery_export_platform_log_proto_init() {
	if File_google_analytics_cloud_bigquery_export_platform_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_analytics_cloud_bigquery_export_platform_log_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExportStatusLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_analytics_cloud_bigquery_export_platform_log_proto_goTypes,
		DependencyIndexes: file_google_analytics_cloud_bigquery_export_platform_log_proto_depIdxs,
		EnumInfos:         file_google_analytics_cloud_bigquery_export_platform_log_proto_enumTypes,
		MessageInfos:      file_google_analytics_cloud_bigquery_export_platform_log_proto_msgTypes,
	}.Build()
	File_google_analytics_cloud_bigquery_export_platform_log_proto = out.File
	file_google_analytics_cloud_bigquery_export_platform_log_proto_rawDesc = nil
	file_google_analytics_cloud_bigquery_export_platform_log_proto_goTypes = nil
	file_google_analytics_cloud_bigquery_export_platform_log_proto_depIdxs = nil
}
